/*
###############################################################
#  Generated by:      Cadence Innovus 21.12-s106_1
#  OS:                Linux x86_64(Host ID vlsi73.ee.iitb.ac.in)
#  Generated on:      Fri Nov 28 23:58:42 2025
#  Design:            onset_detector
#  Command:           saveNetlist physical_design/onset_detector_netlist.v
###############################################################
*/
// Generated by Cadence Genus(TM) Synthesis Solution 21.19-s055_1
// Generated on: Nov 28 2025 22:15:35 IST (Nov 28 2025 16:45:35 UTC)
// Verification Directory fv/onset_detector 
module adder_18bit (
	a, 
	b, 
	sum);
   input [17:0] a;
   input [17:0] b;
   output [17:0] sum;

   // Internal wires
   wire add_6_20_n_0;
   wire add_6_20_n_2;
   wire add_6_20_n_4;
   wire add_6_20_n_6;
   wire add_6_20_n_8;
   wire add_6_20_n_10;
   wire add_6_20_n_12;
   wire add_6_20_n_14;
   wire add_6_20_n_16;
   wire add_6_20_n_18;
   wire add_6_20_n_20;
   wire add_6_20_n_22;
   wire add_6_20_n_24;
   wire add_6_20_n_26;
   wire add_6_20_n_28;
   wire add_6_20_n_30;
   wire add_6_20_n_32;

   XOR3D1 add_6_20_g999__2398 (.A1(a[17]),
	.A2(b[17]),
	.A3(add_6_20_n_32),
	.Z(sum[17]));
   FA1D0 add_6_20_g1000__5107 (.A(b[16]),
	.B(a[16]),
	.CI(add_6_20_n_30),
	.CO(add_6_20_n_32),
	.S(sum[16]));
   FA1D0 add_6_20_g1001__6260 (.A(b[15]),
	.B(a[15]),
	.CI(add_6_20_n_28),
	.CO(add_6_20_n_30),
	.S(sum[15]));
   FA1D0 add_6_20_g1002__4319 (.A(b[14]),
	.B(a[14]),
	.CI(add_6_20_n_26),
	.CO(add_6_20_n_28),
	.S(sum[14]));
   FA1D0 add_6_20_g1003__8428 (.A(b[13]),
	.B(a[13]),
	.CI(add_6_20_n_24),
	.CO(add_6_20_n_26),
	.S(sum[13]));
   FA1D0 add_6_20_g1004__5526 (.A(b[12]),
	.B(a[12]),
	.CI(add_6_20_n_22),
	.CO(add_6_20_n_24),
	.S(sum[12]));
   FA1D0 add_6_20_g1005__6783 (.A(b[11]),
	.B(a[11]),
	.CI(add_6_20_n_20),
	.CO(add_6_20_n_22),
	.S(sum[11]));
   FA1D0 add_6_20_g1006__3680 (.A(b[10]),
	.B(a[10]),
	.CI(add_6_20_n_18),
	.CO(add_6_20_n_20),
	.S(sum[10]));
   FA1D0 add_6_20_g1007__1617 (.A(b[9]),
	.B(a[9]),
	.CI(add_6_20_n_16),
	.CO(add_6_20_n_18),
	.S(sum[9]));
   FA1D0 add_6_20_g1008__2802 (.A(b[8]),
	.B(a[8]),
	.CI(add_6_20_n_14),
	.CO(add_6_20_n_16),
	.S(sum[8]));
   FA1D0 add_6_20_g1009__1705 (.A(b[7]),
	.B(a[7]),
	.CI(add_6_20_n_12),
	.CO(add_6_20_n_14),
	.S(sum[7]));
   FA1D0 add_6_20_g1010__5122 (.A(b[6]),
	.B(a[6]),
	.CI(add_6_20_n_10),
	.CO(add_6_20_n_12),
	.S(sum[6]));
   FA1D0 add_6_20_g1011__8246 (.A(b[5]),
	.B(a[5]),
	.CI(add_6_20_n_8),
	.CO(add_6_20_n_10),
	.S(sum[5]));
   FA1D0 add_6_20_g1012__7098 (.A(add_6_20_n_6),
	.B(b[4]),
	.CI(a[4]),
	.CO(add_6_20_n_8),
	.S(sum[4]));
   FA1D0 add_6_20_g1013__6131 (.A(add_6_20_n_4),
	.B(b[3]),
	.CI(a[3]),
	.CO(add_6_20_n_6),
	.S(sum[3]));
   FA1D0 add_6_20_g1014__1881 (.A(b[2]),
	.B(add_6_20_n_2),
	.CI(a[2]),
	.CO(add_6_20_n_4),
	.S(sum[2]));
   FA1D0 add_6_20_g1015__5115 (.A(b[1]),
	.B(add_6_20_n_0),
	.CI(a[1]),
	.CO(add_6_20_n_2),
	.S(sum[1]));
   HA1D0 add_6_20_g1016__7482 (.A(b[0]),
	.B(a[0]),
	.CO(add_6_20_n_0),
	.S(sum[0]));
endmodule

module mult10X8 (
	a, 
	b, 
	product);
   input [9:0] a;
   input [7:0] b;
   output [17:0] product;

   // Internal wires
   wire mul_6_24_n_0;
   wire mul_6_24_n_1;
   wire mul_6_24_n_2;
   wire mul_6_24_n_3;
   wire mul_6_24_n_4;
   wire mul_6_24_n_5;
   wire mul_6_24_n_6;
   wire mul_6_24_n_7;
   wire mul_6_24_n_8;
   wire mul_6_24_n_9;
   wire mul_6_24_n_10;
   wire mul_6_24_n_11;
   wire mul_6_24_n_12;
   wire mul_6_24_n_13;
   wire mul_6_24_n_14;
   wire mul_6_24_n_15;
   wire mul_6_24_n_16;
   wire mul_6_24_n_17;
   wire mul_6_24_n_18;
   wire mul_6_24_n_19;
   wire mul_6_24_n_20;
   wire mul_6_24_n_21;
   wire mul_6_24_n_22;
   wire mul_6_24_n_23;
   wire mul_6_24_n_24;
   wire mul_6_24_n_25;
   wire mul_6_24_n_27;
   wire mul_6_24_n_28;
   wire mul_6_24_n_29;
   wire mul_6_24_n_30;
   wire mul_6_24_n_31;
   wire mul_6_24_n_32;
   wire mul_6_24_n_33;
   wire mul_6_24_n_34;
   wire mul_6_24_n_35;
   wire mul_6_24_n_36;
   wire mul_6_24_n_37;
   wire mul_6_24_n_38;
   wire mul_6_24_n_39;
   wire mul_6_24_n_40;
   wire mul_6_24_n_41;
   wire mul_6_24_n_42;
   wire mul_6_24_n_43;
   wire mul_6_24_n_44;
   wire mul_6_24_n_45;
   wire mul_6_24_n_46;
   wire mul_6_24_n_47;
   wire mul_6_24_n_48;
   wire mul_6_24_n_49;
   wire mul_6_24_n_50;
   wire mul_6_24_n_51;
   wire mul_6_24_n_52;
   wire mul_6_24_n_53;
   wire mul_6_24_n_54;
   wire mul_6_24_n_55;
   wire mul_6_24_n_56;
   wire mul_6_24_n_57;
   wire mul_6_24_n_58;
   wire mul_6_24_n_59;
   wire mul_6_24_n_60;
   wire mul_6_24_n_61;
   wire mul_6_24_n_62;
   wire mul_6_24_n_63;
   wire mul_6_24_n_64;
   wire mul_6_24_n_65;
   wire mul_6_24_n_66;
   wire mul_6_24_n_67;
   wire mul_6_24_n_68;
   wire mul_6_24_n_69;
   wire mul_6_24_n_70;
   wire mul_6_24_n_71;
   wire mul_6_24_n_73;
   wire mul_6_24_n_74;
   wire mul_6_24_n_75;
   wire mul_6_24_n_76;
   wire mul_6_24_n_77;
   wire mul_6_24_n_78;
   wire mul_6_24_n_79;
   wire mul_6_24_n_80;
   wire mul_6_24_n_81;
   wire mul_6_24_n_82;
   wire mul_6_24_n_83;
   wire mul_6_24_n_84;
   wire mul_6_24_n_85;
   wire mul_6_24_n_86;
   wire mul_6_24_n_87;
   wire mul_6_24_n_89;
   wire mul_6_24_n_90;
   wire mul_6_24_n_91;
   wire mul_6_24_n_92;
   wire mul_6_24_n_93;
   wire mul_6_24_n_94;
   wire mul_6_24_n_96;
   wire mul_6_24_n_98;
   wire mul_6_24_n_100;
   wire mul_6_24_n_104;
   wire mul_6_24_n_106;
   wire mul_6_24_n_110;
   wire mul_6_24_n_112;
   wire mul_6_24_n_114;
   wire mul_6_24_n_116;
   wire mul_6_24_n_118;
   wire mul_6_24_n_122;
   wire mul_6_24_n_123;
   wire mul_6_24_n_124;
   wire mul_6_24_n_125;
   wire mul_6_24_n_126;
   wire mul_6_24_n_127;
   wire mul_6_24_n_128;
   wire mul_6_24_n_129;
   wire mul_6_24_n_130;
   wire mul_6_24_n_131;
   wire mul_6_24_n_132;
   wire mul_6_24_n_133;
   wire mul_6_24_n_134;
   wire mul_6_24_n_135;
   wire mul_6_24_n_136;
   wire mul_6_24_n_137;
   wire mul_6_24_n_138;
   wire mul_6_24_n_139;
   wire mul_6_24_n_140;
   wire mul_6_24_n_141;
   wire mul_6_24_n_142;
   wire mul_6_24_n_143;
   wire mul_6_24_n_144;
   wire mul_6_24_n_145;
   wire mul_6_24_n_146;
   wire mul_6_24_n_147;
   wire mul_6_24_n_148;
   wire mul_6_24_n_149;
   wire mul_6_24_n_150;
   wire mul_6_24_n_151;
   wire mul_6_24_n_152;
   wire mul_6_24_n_153;
   wire mul_6_24_n_154;
   wire mul_6_24_n_155;
   wire mul_6_24_n_156;
   wire mul_6_24_n_157;
   wire mul_6_24_n_158;
   wire mul_6_24_n_159;
   wire mul_6_24_n_160;
   wire mul_6_24_n_161;
   wire mul_6_24_n_162;
   wire mul_6_24_n_163;
   wire mul_6_24_n_164;
   wire mul_6_24_n_165;
   wire mul_6_24_n_166;
   wire mul_6_24_n_167;
   wire mul_6_24_n_168;
   wire mul_6_24_n_169;
   wire mul_6_24_n_170;
   wire mul_6_24_n_171;
   wire mul_6_24_n_172;
   wire mul_6_24_n_173;
   wire mul_6_24_n_174;
   wire mul_6_24_n_175;
   wire mul_6_24_n_177;
   wire mul_6_24_n_178;
   wire mul_6_24_n_179;
   wire mul_6_24_n_180;
   wire mul_6_24_n_181;
   wire mul_6_24_n_182;
   wire mul_6_24_n_183;
   wire mul_6_24_n_184;
   wire mul_6_24_n_185;
   wire mul_6_24_n_187;
   wire mul_6_24_n_188;
   wire mul_6_24_n_191;
   wire mul_6_24_n_192;
   wire mul_6_24_n_193;
   wire mul_6_24_n_194;
   wire mul_6_24_n_195;
   wire n_213;
   wire n_215;
   wire n_216;
   wire n_218;

   CMPE42D1 mul_6_24_cdnca_004_0__4733 (.A(mul_6_24_n_68),
	.B(mul_6_24_n_33),
	.C(mul_6_24_n_61),
	.CIX(mul_6_24_n_82),
	.CO(mul_6_24_n_173),
	.COX(mul_6_24_n_171),
	.D(mul_6_24_n_79),
	.S(mul_6_24_n_122));
   CMPE42D1 mul_6_24_cdnca_005_0__6161 (.A(mul_6_24_n_64),
	.B(mul_6_24_n_68),
	.C(mul_6_24_n_62),
	.CIX(mul_6_24_n_50),
	.CO(mul_6_24_n_170),
	.COX(mul_6_24_n_169),
	.D(mul_6_24_n_84),
	.S(mul_6_24_n_168));
   CMPE42D1 mul_6_24_cdnca_006_0__9315 (.A(mul_6_24_n_66),
	.B(mul_6_24_n_64),
	.C(mul_6_24_n_25),
	.CIX(mul_6_24_n_27),
	.CO(mul_6_24_n_167),
	.COX(mul_6_24_n_166),
	.D(mul_6_24_n_23),
	.S(mul_6_24_n_165));
   CMPE42D1 mul_6_24_cdnca_006_1__9945 (.A(mul_6_24_n_83),
	.B(mul_6_24_n_76),
	.C(mul_6_24_n_165),
	.CIX(mul_6_24_n_169),
	.CO(mul_6_24_n_175),
	.COX(mul_6_24_n_146),
	.D(mul_6_24_n_170),
	.S(mul_6_24_n_185));
   CMPE42D1 mul_6_24_cdnca_007_0__2883 (.A(mul_6_24_n_65),
	.B(mul_6_24_n_21),
	.C(mul_6_24_n_66),
	.CIX(mul_6_24_n_12),
	.CO(mul_6_24_n_164),
	.COX(mul_6_24_n_163),
	.D(mul_6_24_n_58),
	.S(mul_6_24_n_162));
   CMPE42D1 mul_6_24_cdnca_007_1__2346 (.A(mul_6_24_n_18),
	.B(mul_6_24_n_75),
	.C(mul_6_24_n_74),
	.CIX(mul_6_24_n_162),
	.CO(mul_6_24_n_145),
	.COX(mul_6_24_n_144),
	.D(mul_6_24_n_166),
	.S(mul_6_24_n_143));
   CMPE42D1 mul_6_24_cdnca_008_0__1666 (.A(mul_6_24_n_20),
	.B(mul_6_24_n_15),
	.C(mul_6_24_n_69),
	.CIX(mul_6_24_n_47),
	.CO(mul_6_24_n_161),
	.COX(mul_6_24_n_160),
	.D(mul_6_24_n_65),
	.S(mul_6_24_n_159));
   CMPE42D1 mul_6_24_cdnca_008_1__7410 (.A(mul_6_24_n_51),
	.B(mul_6_24_n_44),
	.C(mul_6_24_n_11),
	.CIX(mul_6_24_n_73),
	.CO(mul_6_24_n_142),
	.COX(mul_6_24_n_141),
	.D(mul_6_24_n_159),
	.S(mul_6_24_n_140));
   CMPE42D1 mul_6_24_cdnca_008_2__6417 (.A(mul_6_24_n_163),
	.B(mul_6_24_n_164),
	.C(mul_6_24_n_140),
	.CIX(mul_6_24_n_144),
	.CO(mul_6_24_n_177),
	.COX(mul_6_24_n_130),
	.D(mul_6_24_n_145),
	.S(mul_6_24_n_187));
   CMPE42D1 mul_6_24_cdnca_009_0__5477 (.A(mul_6_24_n_49),
	.B(mul_6_24_n_53),
	.C(mul_6_24_n_63),
	.CIX(mul_6_24_n_57),
	.CO(mul_6_24_n_158),
	.COX(mul_6_24_n_157),
	.D(mul_6_24_n_69),
	.S(mul_6_24_n_156));
   CMPE42D1 mul_6_24_cdnca_009_1__2398 (.A(mul_6_24_n_46),
	.B(mul_6_24_n_17),
	.C(mul_6_24_n_41),
	.CIX(mul_6_24_n_156),
	.CO(mul_6_24_n_139),
	.COX(mul_6_24_n_138),
	.D(mul_6_24_n_160),
	.S(mul_6_24_n_137));
   CMPE42D1 mul_6_24_cdnca_009_2__5107 (.A(mul_6_24_n_161),
	.B(mul_6_24_n_141),
	.C(mul_6_24_n_137),
	.CIX(mul_6_24_n_142),
	.CO(mul_6_24_n_178),
	.COX(mul_6_24_n_124),
	.D(mul_6_24_n_130),
	.S(mul_6_24_n_188));
   CMPE42D1 mul_6_24_cdnca_010_0__6260 (.A(mul_6_24_n_63),
	.B(mul_6_24_n_19),
	.C(mul_6_24_n_30),
	.CIX(mul_6_24_n_16),
	.CO(mul_6_24_n_155),
	.COX(mul_6_24_n_154),
	.D(mul_6_24_n_40),
	.S(mul_6_24_n_153));
   CMPE42D1 mul_6_24_cdnca_010_1__4319 (.A(mul_6_24_n_78),
	.B(mul_6_24_n_153),
	.C(mul_6_24_n_157),
	.CIX(mul_6_24_n_158),
	.CO(mul_6_24_n_129),
	.COX(mul_6_24_n_128),
	.D(mul_6_24_n_138),
	.S(mul_6_24_n_127));
   CMPE42D1 mul_6_24_cdnca_011_0__8428 (.A(mul_6_24_n_43),
	.B(mul_6_24_n_32),
	.C(mul_6_24_n_56),
	.CIX(mul_6_24_n_60),
	.CO(mul_6_24_n_152),
	.COX(mul_6_24_n_151),
	.D(mul_6_24_n_30),
	.S(mul_6_24_n_150));
   CMPE42D1 mul_6_24_cdnca_011_1__5526 (.A(mul_6_24_n_42),
	.B(mul_6_24_n_77),
	.C(mul_6_24_n_150),
	.CIX(mul_6_24_n_154),
	.CO(mul_6_24_n_136),
	.COX(mul_6_24_n_135),
	.D(mul_6_24_n_155),
	.S(mul_6_24_n_134));
   CMPE42D1 mul_6_24_cdnca_012_0__6783 (.A(mul_6_24_n_31),
	.B(mul_6_24_n_32),
	.C(mul_6_24_n_52),
	.CIX(mul_6_24_n_54),
	.CO(mul_6_24_n_149),
	.COX(mul_6_24_n_148),
	.D(mul_6_24_n_59),
	.S(mul_6_24_n_147));
   CMPE42D1 mul_6_24_cdnca_012_1__3680 (.A(mul_6_24_n_147),
	.B(mul_6_24_n_151),
	.C(mul_6_24_n_152),
	.CIX(mul_6_24_n_135),
	.CO(mul_6_24_n_181),
	.COX(mul_6_24_n_126),
	.D(mul_6_24_n_136),
	.S(mul_6_24_n_180));
   CMPE42D1 mul_6_24_cdnca_013_0__1617 (.A(mul_6_24_n_31),
	.B(mul_6_24_n_55),
	.C(mul_6_24_n_22),
	.CIX(mul_6_24_n_48),
	.CO(mul_6_24_n_133),
	.COX(mul_6_24_n_132),
	.D(mul_6_24_n_148),
	.S(mul_6_24_n_131));
   CMPE42D1 mul_6_24_cdnca_014_0__2802 (.A(mul_6_24_n_14),
	.B(mul_6_24_n_45),
	.C(mul_6_24_n_9),
	.CIX(mul_6_24_n_132),
	.CO(mul_6_24_n_183),
	.COX(mul_6_24_n_125),
	.D(mul_6_24_n_133),
	.S(mul_6_24_n_182));
   FA1D0 mul_6_24_cdnfadd_003_0__1705 (.A(mul_6_24_n_33),
	.B(mul_6_24_n_13),
	.CI(mul_6_24_n_80),
	.CO(mul_6_24_n_172),
	.S(mul_6_24_n_123));
   FA1D0 mul_6_24_cdnfadd_005_1__5122 (.A(mul_6_24_n_81),
	.B(mul_6_24_n_168),
	.CI(mul_6_24_n_171),
	.CO(mul_6_24_n_174),
	.S(mul_6_24_n_184));
   FA1D0 mul_6_24_cdnfadd_011_2__6131 (.A(mul_6_24_n_134),
	.B(mul_6_24_n_128),
	.CI(mul_6_24_n_129),
	.CO(mul_6_24_n_191),
	.S(mul_6_24_n_179));
   FA1D0 mul_6_24_cdnfadd_013_1__1881 (.A(mul_6_24_n_149),
	.B(mul_6_24_n_131),
	.CI(mul_6_24_n_126),
	.CO(mul_6_24_n_193),
	.S(mul_6_24_n_192));
   FA1D0 mul_6_24_cdnfadd_015_0__5115 (.A(mul_6_24_n_10),
	.B(mul_6_24_n_24),
	.CI(mul_6_24_n_125),
	.CO(mul_6_24_n_195),
	.S(mul_6_24_n_194));
   FA1D0 mul_6_24_g982__7482 (.A(mul_6_24_n_195),
	.B(mul_6_24_n_0),
	.CI(mul_6_24_n_118),
	.CO(product[17]),
	.S(product[16]));
   FA1D0 mul_6_24_g983__4733 (.A(mul_6_24_n_183),
	.B(mul_6_24_n_194),
	.CI(mul_6_24_n_116),
	.CO(mul_6_24_n_118),
	.S(product[15]));
   FA1D0 mul_6_24_g984__6161 (.A(mul_6_24_n_193),
	.B(mul_6_24_n_182),
	.CI(mul_6_24_n_114),
	.CO(mul_6_24_n_116),
	.S(product[14]));
   FA1D0 mul_6_24_g985__9315 (.A(mul_6_24_n_181),
	.B(mul_6_24_n_192),
	.CI(mul_6_24_n_112),
	.CO(mul_6_24_n_114),
	.S(product[13]));
   FA1D0 mul_6_24_g986__9945 (.A(mul_6_24_n_180),
	.B(mul_6_24_n_191),
	.CI(mul_6_24_n_110),
	.CO(mul_6_24_n_112),
	.S(product[12]));
   FA1D0 mul_6_24_g987__2883 (.A(n_215),
	.B(mul_6_24_n_179),
	.CI(n_213),
	.CO(mul_6_24_n_110),
	.S(product[11]));
   FA1D0 mul_6_24_g989__1666 (.A(mul_6_24_n_188),
	.B(mul_6_24_n_177),
	.CI(mul_6_24_n_104),
	.CO(mul_6_24_n_106),
	.S(product[9]));
   FA1D0 mul_6_24_g990__7410 (.A(n_216),
	.B(n_218),
	.CI(mul_6_24_n_187),
	.CO(mul_6_24_n_104),
	.S(product[8]));
   FA1D0 mul_6_24_g992__5477 (.A(mul_6_24_n_185),
	.B(mul_6_24_n_174),
	.CI(mul_6_24_n_98),
	.CO(mul_6_24_n_100),
	.S(product[6]));
   FA1D0 mul_6_24_g993__2398 (.A(mul_6_24_n_96),
	.B(mul_6_24_n_173),
	.CI(mul_6_24_n_184),
	.CO(mul_6_24_n_98),
	.S(product[5]));
   FA1D0 mul_6_24_g994__5107 (.A(mul_6_24_n_93),
	.B(mul_6_24_n_172),
	.CI(mul_6_24_n_122),
	.CO(mul_6_24_n_96),
	.S(product[4]));
   XNR2D1 mul_6_24_g995__6260 (.A1(mul_6_24_n_94),
	.A2(mul_6_24_n_87),
	.ZN(product[3]));
   NR2XD0 mul_6_24_g996__4319 (.A1(mul_6_24_n_91),
	.A2(mul_6_24_n_90),
	.ZN(mul_6_24_n_94));
   OAI21D1 mul_6_24_g997__8428 (.A1(mul_6_24_n_90),
	.A2(mul_6_24_n_87),
	.B(mul_6_24_n_92),
	.ZN(mul_6_24_n_93));
   INVD1 mul_6_24_g998 (.I(mul_6_24_n_91),
	.ZN(mul_6_24_n_92));
   NR3D0 mul_6_24_g999__5526 (.A1(mul_6_24_n_89),
	.A2(mul_6_24_n_29),
	.A3(mul_6_24_n_28),
	.ZN(mul_6_24_n_91));
   OA21D1 mul_6_24_g1000__6783 (.A1(mul_6_24_n_29),
	.A2(mul_6_24_n_28),
	.B(mul_6_24_n_89),
	.Z(mul_6_24_n_90));
   INVD1 mul_6_24_g1001 (.I(mul_6_24_n_123),
	.ZN(mul_6_24_n_89));
   CKXOR2D1 mul_6_24_g1002__3680 (.A1(mul_6_24_n_86),
	.A2(mul_6_24_n_70),
	.Z(product[2]));
   NR2XD0 mul_6_24_g1003__1617 (.A1(mul_6_24_n_85),
	.A2(mul_6_24_n_70),
	.ZN(mul_6_24_n_87));
   HA1D0 mul_6_24_g1004__2802 (.A(mul_6_24_n_8),
	.B(mul_6_24_n_71),
	.CO(mul_6_24_n_85),
	.S(mul_6_24_n_86));
   HA1D0 mul_6_24_g1005__1705 (.A(mul_6_24_n_2),
	.B(mul_6_24_n_3),
	.CO(mul_6_24_n_83),
	.S(mul_6_24_n_84));
   HA1D0 mul_6_24_g1006__5122 (.A(mul_6_24_n_36),
	.B(mul_6_24_n_7),
	.CO(mul_6_24_n_81),
	.S(mul_6_24_n_82));
   HA1D0 mul_6_24_g1007__8246 (.A(mul_6_24_n_37),
	.B(mul_6_24_n_5),
	.CO(mul_6_24_n_79),
	.S(mul_6_24_n_80));
   HA1D0 mul_6_24_g1008__7098 (.A(mul_6_24_n_1),
	.B(mul_6_24_n_39),
	.CO(mul_6_24_n_77),
	.S(mul_6_24_n_78));
   HA1D0 mul_6_24_g1009__6131 (.A(mul_6_24_n_4),
	.B(mul_6_24_n_35),
	.CO(mul_6_24_n_75),
	.S(mul_6_24_n_76));
   HA1D0 mul_6_24_g1010__1881 (.A(mul_6_24_n_38),
	.B(mul_6_24_n_6),
	.CO(mul_6_24_n_73),
	.S(mul_6_24_n_74));
   AOI21D1 mul_6_24_g1011__5115 (.A1(mul_6_24_n_67),
	.A2(mul_6_24_n_34),
	.B(mul_6_24_n_70),
	.ZN(product[1]));
   CKXOR2D1 mul_6_24_g1012__7482 (.A1(mul_6_24_n_28),
	.A2(mul_6_24_n_29),
	.Z(mul_6_24_n_71));
   NR2XD0 mul_6_24_g1013__4733 (.A1(mul_6_24_n_67),
	.A2(mul_6_24_n_34),
	.ZN(mul_6_24_n_70));
   AN2XD1 mul_6_24_g1014__6161 (.A1(a[3]),
	.A2(b[2]),
	.Z(mul_6_24_n_62));
   AN2XD1 mul_6_24_g1015__9315 (.A1(a[2]),
	.A2(b[2]),
	.Z(mul_6_24_n_61));
   AN2XD1 mul_6_24_g1016__9945 (.A1(a[5]),
	.A2(b[6]),
	.Z(mul_6_24_n_60));
   AN2XD1 mul_6_24_g1017__2883 (.A1(a[7]),
	.A2(b[5]),
	.Z(mul_6_24_n_59));
   AN2XD1 mul_6_24_g1018__2346 (.A1(a[2]),
	.A2(b[5]),
	.Z(mul_6_24_n_58));
   AN2XD1 mul_6_24_g1019__1666 (.A1(a[2]),
	.A2(b[7]),
	.Z(mul_6_24_n_57));
   AN2XD1 mul_6_24_g1020__7410 (.A1(a[6]),
	.A2(b[5]),
	.Z(mul_6_24_n_56));
   AN2XD1 mul_6_24_g1021__6417 (.A1(a[8]),
	.A2(b[5]),
	.Z(mul_6_24_n_55));
   AN2XD1 mul_6_24_g1022__5477 (.A1(a[5]),
	.A2(b[7]),
	.Z(mul_6_24_n_54));
   AN2XD1 mul_6_24_g1023__2398 (.A1(a[8]),
	.A2(b[1]),
	.Z(mul_6_24_n_53));
   AN2XD1 mul_6_24_g1024__5107 (.A1(a[6]),
	.A2(b[6]),
	.Z(mul_6_24_n_52));
   AN2XD1 mul_6_24_g1025__6260 (.A1(a[6]),
	.A2(b[2]),
	.Z(mul_6_24_n_51));
   AN2XD1 mul_6_24_g1026__4319 (.A1(a[0]),
	.A2(b[5]),
	.Z(mul_6_24_n_50));
   AN2XD1 mul_6_24_g1027__8428 (.A1(a[9]),
	.A2(b[0]),
	.Z(mul_6_24_n_49));
   AN2XD1 mul_6_24_g1028__5526 (.A1(a[7]),
	.A2(b[6]),
	.Z(mul_6_24_n_48));
   AN2XD1 mul_6_24_g1029__6783 (.A1(a[1]),
	.A2(b[7]),
	.Z(mul_6_24_n_47));
   AN2XD1 mul_6_24_g1030__3680 (.A1(a[7]),
	.A2(b[2]),
	.Z(mul_6_24_n_46));
   AN2XD1 mul_6_24_g1031__1617 (.A1(a[8]),
	.A2(b[6]),
	.Z(mul_6_24_n_45));
   AN2XD1 mul_6_24_g1032__2802 (.A1(a[3]),
	.A2(b[5]),
	.Z(mul_6_24_n_44));
   AN2XD1 mul_6_24_g1033__1705 (.A1(a[9]),
	.A2(b[2]),
	.Z(mul_6_24_n_43));
   AN2XD1 mul_6_24_g1034__5122 (.A1(a[4]),
	.A2(b[7]),
	.Z(mul_6_24_n_42));
   AN2XD1 mul_6_24_g1035__8246 (.A1(a[3]),
	.A2(b[6]),
	.Z(mul_6_24_n_41));
   AN2XD1 mul_6_24_g1036__7098 (.A1(a[3]),
	.A2(b[7]),
	.Z(mul_6_24_n_40));
   AN2XD1 mul_6_24_g1037__6131 (.A1(a[9]),
	.A2(b[1]),
	.Z(mul_6_24_n_39));
   AN2XD1 mul_6_24_g1038__1881 (.A1(a[5]),
	.A2(b[3]),
	.Z(mul_6_24_n_69));
   AN2XD1 mul_6_24_g1039__5115 (.A1(a[1]),
	.A2(b[3]),
	.Z(mul_6_24_n_68));
   CKND2D1 mul_6_24_g1040__7482 (.A1(a[1]),
	.A2(b[0]),
	.ZN(mul_6_24_n_67));
   AN2XD1 mul_6_24_g1041__4733 (.A1(a[6]),
	.A2(b[1]),
	.Z(mul_6_24_n_38));
   AN2XD1 mul_6_24_g1042__6161 (.A1(a[3]),
	.A2(b[3]),
	.Z(mul_6_24_n_66));
   AN2XD1 mul_6_24_g1043__9315 (.A1(a[2]),
	.A2(b[1]),
	.Z(mul_6_24_n_37));
   AN2XD1 mul_6_24_g1044__9945 (.A1(a[4]),
	.A2(b[3]),
	.Z(mul_6_24_n_65));
   AN2XD1 mul_6_24_g1045__2883 (.A1(a[3]),
	.A2(b[1]),
	.Z(mul_6_24_n_36));
   AN2XD1 mul_6_24_g1046__2346 (.A1(a[6]),
	.A2(b[0]),
	.Z(mul_6_24_n_35));
   AN2XD1 mul_6_24_g1047__1666 (.A1(a[2]),
	.A2(b[3]),
	.Z(mul_6_24_n_64));
   AN2XD1 mul_6_24_g1048__7410 (.A1(a[6]),
	.A2(b[3]),
	.Z(mul_6_24_n_63));
   AN2XD1 mul_6_24_g1049__6417 (.A1(a[1]),
	.A2(b[5]),
	.Z(mul_6_24_n_27));
   AN2XD1 mul_6_24_g1050__5477 (.A1(a[0]),
	.A2(b[0]),
	.Z(product[0]));
   AN2XD1 mul_6_24_g1051__2398 (.A1(a[4]),
	.A2(b[2]),
	.Z(mul_6_24_n_25));
   AN2XD1 mul_6_24_g1052__5107 (.A1(a[8]),
	.A2(b[7]),
	.Z(mul_6_24_n_24));
   AN2XD1 mul_6_24_g1053__6260 (.A1(a[0]),
	.A2(b[6]),
	.Z(mul_6_24_n_23));
   AN2XD1 mul_6_24_g1054__4319 (.A1(a[6]),
	.A2(b[7]),
	.Z(mul_6_24_n_22));
   AN2XD1 mul_6_24_g1055__8428 (.A1(a[0]),
	.A2(b[7]),
	.Z(mul_6_24_n_21));
   AN2XD1 mul_6_24_g1056__5526 (.A1(a[8]),
	.A2(b[0]),
	.Z(mul_6_24_n_20));
   AN2XD1 mul_6_24_g1057__6783 (.A1(a[5]),
	.A2(b[5]),
	.Z(mul_6_24_n_19));
   AN2XD1 mul_6_24_g1058__3680 (.A1(a[1]),
	.A2(b[6]),
	.Z(mul_6_24_n_18));
   AN2XD1 mul_6_24_g1059__1617 (.A1(a[4]),
	.A2(b[5]),
	.Z(mul_6_24_n_17));
   AN2XD1 mul_6_24_g1060__2802 (.A1(a[4]),
	.A2(b[6]),
	.Z(mul_6_24_n_16));
   AN2XD1 mul_6_24_g1061__1705 (.A1(a[7]),
	.A2(b[1]),
	.Z(mul_6_24_n_15));
   AN2XD1 mul_6_24_g1062__5122 (.A1(a[9]),
	.A2(b[5]),
	.Z(mul_6_24_n_14));
   AN2XD1 mul_6_24_g1063__8246 (.A1(a[1]),
	.A2(b[2]),
	.Z(mul_6_24_n_13));
   AN2XD1 mul_6_24_g1064__7098 (.A1(a[5]),
	.A2(b[2]),
	.Z(mul_6_24_n_12));
   AN2XD1 mul_6_24_g1065__6131 (.A1(a[2]),
	.A2(b[6]),
	.Z(mul_6_24_n_11));
   AN2XD1 mul_6_24_g1066__1881 (.A1(a[9]),
	.A2(b[6]),
	.Z(mul_6_24_n_10));
   AN2XD1 mul_6_24_g1067__5115 (.A1(a[7]),
	.A2(b[7]),
	.Z(mul_6_24_n_9));
   AN2XD1 mul_6_24_g1068__7482 (.A1(a[1]),
	.A2(b[1]),
	.Z(mul_6_24_n_8));
   CKND2D1 mul_6_24_g1069__4733 (.A1(a[0]),
	.A2(b[1]),
	.ZN(mul_6_24_n_34));
   AN2XD1 mul_6_24_g1070__6161 (.A1(a[4]),
	.A2(b[0]),
	.Z(mul_6_24_n_7));
   AN2XD1 mul_6_24_g1071__9315 (.A1(a[7]),
	.A2(b[0]),
	.Z(mul_6_24_n_6));
   AN2XD1 mul_6_24_g1072__9945 (.A1(a[3]),
	.A2(b[0]),
	.Z(mul_6_24_n_5));
   AN2XD1 mul_6_24_g1073__2883 (.A1(a[5]),
	.A2(b[1]),
	.Z(mul_6_24_n_4));
   AN2XD1 mul_6_24_g1074__2346 (.A1(a[0]),
	.A2(b[3]),
	.Z(mul_6_24_n_33));
   AN2XD1 mul_6_24_g1075__1666 (.A1(a[5]),
	.A2(b[0]),
	.Z(mul_6_24_n_3));
   AN2XD1 mul_6_24_g1076__7410 (.A1(a[4]),
	.A2(b[1]),
	.Z(mul_6_24_n_2));
   AN2XD1 mul_6_24_g1077__6417 (.A1(a[8]),
	.A2(b[3]),
	.Z(mul_6_24_n_32));
   AN2XD1 mul_6_24_g1078__5477 (.A1(a[8]),
	.A2(b[2]),
	.Z(mul_6_24_n_1));
   AN2XD1 mul_6_24_g1079__2398 (.A1(a[9]),
	.A2(b[3]),
	.Z(mul_6_24_n_31));
   AN2XD1 mul_6_24_g1080__5107 (.A1(a[9]),
	.A2(b[7]),
	.Z(mul_6_24_n_0));
   AN2XD1 mul_6_24_g1081__6260 (.A1(a[7]),
	.A2(b[3]),
	.Z(mul_6_24_n_30));
   ND2D1 mul_6_24_g1082__4319 (.A1(a[0]),
	.A2(b[2]),
	.ZN(mul_6_24_n_29));
   ND2D1 mul_6_24_g1083__8428 (.A1(a[2]),
	.A2(b[0]),
	.ZN(mul_6_24_n_28));
   CMPE42D1 g2 (.A(mul_6_24_n_139),
	.B(mul_6_24_n_127),
	.C(mul_6_24_n_124),
	.CIX(mul_6_24_n_178),
	.CO(n_213),
	.COX(n_215),
	.D(mul_6_24_n_106),
	.S(product[10]));
   CMPE42D1 g1084 (.A(mul_6_24_n_167),
	.B(mul_6_24_n_143),
	.C(mul_6_24_n_146),
	.CIX(mul_6_24_n_175),
	.CO(n_216),
	.COX(n_218),
	.D(mul_6_24_n_100),
	.S(product[7]));
endmodule

module adder_18bit_130 (
	a, 
	b, 
	sum);
   input [17:0] a;
   input [17:0] b;
   output [17:0] sum;

   // Internal wires
   wire add_6_20_n_0;
   wire add_6_20_n_2;
   wire add_6_20_n_4;
   wire add_6_20_n_6;
   wire add_6_20_n_8;
   wire add_6_20_n_10;
   wire add_6_20_n_12;
   wire add_6_20_n_14;
   wire add_6_20_n_16;
   wire add_6_20_n_18;
   wire add_6_20_n_20;
   wire add_6_20_n_22;
   wire add_6_20_n_24;
   wire add_6_20_n_26;
   wire add_6_20_n_28;
   wire add_6_20_n_30;
   wire add_6_20_n_32;

   XOR3D1 add_6_20_g999__5526 (.A1(a[17]),
	.A2(b[17]),
	.A3(add_6_20_n_32),
	.Z(sum[17]));
   FA1D0 add_6_20_g1000__6783 (.A(b[16]),
	.B(a[16]),
	.CI(add_6_20_n_30),
	.CO(add_6_20_n_32),
	.S(sum[16]));
   FA1D0 add_6_20_g1001__3680 (.A(b[15]),
	.B(a[15]),
	.CI(add_6_20_n_28),
	.CO(add_6_20_n_30),
	.S(sum[15]));
   FA1D0 add_6_20_g1002__1617 (.A(b[14]),
	.B(a[14]),
	.CI(add_6_20_n_26),
	.CO(add_6_20_n_28),
	.S(sum[14]));
   FA1D0 add_6_20_g1003__2802 (.A(b[13]),
	.B(a[13]),
	.CI(add_6_20_n_24),
	.CO(add_6_20_n_26),
	.S(sum[13]));
   FA1D0 add_6_20_g1004__1705 (.A(b[12]),
	.B(a[12]),
	.CI(add_6_20_n_22),
	.CO(add_6_20_n_24),
	.S(sum[12]));
   FA1D0 add_6_20_g1005__5122 (.A(b[11]),
	.B(a[11]),
	.CI(add_6_20_n_20),
	.CO(add_6_20_n_22),
	.S(sum[11]));
   FA1D0 add_6_20_g1006__8246 (.A(b[10]),
	.B(a[10]),
	.CI(add_6_20_n_18),
	.CO(add_6_20_n_20),
	.S(sum[10]));
   FA1D0 add_6_20_g1007__7098 (.A(b[9]),
	.B(a[9]),
	.CI(add_6_20_n_16),
	.CO(add_6_20_n_18),
	.S(sum[9]));
   FA1D0 add_6_20_g1008__6131 (.A(b[8]),
	.B(a[8]),
	.CI(add_6_20_n_14),
	.CO(add_6_20_n_16),
	.S(sum[8]));
   FA1D0 add_6_20_g1009__1881 (.A(b[7]),
	.B(a[7]),
	.CI(add_6_20_n_12),
	.CO(add_6_20_n_14),
	.S(sum[7]));
   FA1D0 add_6_20_g1010__5115 (.A(b[6]),
	.B(a[6]),
	.CI(add_6_20_n_10),
	.CO(add_6_20_n_12),
	.S(sum[6]));
   FA1D0 add_6_20_g1011__7482 (.A(b[5]),
	.B(a[5]),
	.CI(add_6_20_n_8),
	.CO(add_6_20_n_10),
	.S(sum[5]));
   FA1D0 add_6_20_g1012__4733 (.A(add_6_20_n_6),
	.B(b[4]),
	.CI(a[4]),
	.CO(add_6_20_n_8),
	.S(sum[4]));
   FA1D0 add_6_20_g1013__6161 (.A(add_6_20_n_4),
	.B(b[3]),
	.CI(a[3]),
	.CO(add_6_20_n_6),
	.S(sum[3]));
   FA1D0 add_6_20_g1014__9315 (.A(b[2]),
	.B(add_6_20_n_2),
	.CI(a[2]),
	.CO(add_6_20_n_4),
	.S(sum[2]));
   FA1D0 add_6_20_g1015__9945 (.A(b[1]),
	.B(add_6_20_n_0),
	.CI(a[1]),
	.CO(add_6_20_n_2),
	.S(sum[1]));
   HA1D0 add_6_20_g1016__2883 (.A(b[0]),
	.B(a[0]),
	.CO(add_6_20_n_0),
	.S(sum[0]));
endmodule

module mult10X8_132 (
	a, 
	b, 
	product);
   input [9:0] a;
   input [7:0] b;
   output [17:0] product;

   // Internal wires
   wire mul_6_24_n_0;
   wire mul_6_24_n_1;
   wire mul_6_24_n_2;
   wire mul_6_24_n_3;
   wire mul_6_24_n_4;
   wire mul_6_24_n_5;
   wire mul_6_24_n_6;
   wire mul_6_24_n_7;
   wire mul_6_24_n_8;
   wire mul_6_24_n_9;
   wire mul_6_24_n_10;
   wire mul_6_24_n_11;
   wire mul_6_24_n_12;
   wire mul_6_24_n_13;
   wire mul_6_24_n_14;
   wire mul_6_24_n_15;
   wire mul_6_24_n_16;
   wire mul_6_24_n_17;
   wire mul_6_24_n_18;
   wire mul_6_24_n_19;
   wire mul_6_24_n_20;
   wire mul_6_24_n_21;
   wire mul_6_24_n_22;
   wire mul_6_24_n_23;
   wire mul_6_24_n_24;
   wire mul_6_24_n_25;
   wire mul_6_24_n_27;
   wire mul_6_24_n_28;
   wire mul_6_24_n_29;
   wire mul_6_24_n_30;
   wire mul_6_24_n_31;
   wire mul_6_24_n_32;
   wire mul_6_24_n_33;
   wire mul_6_24_n_34;
   wire mul_6_24_n_35;
   wire mul_6_24_n_36;
   wire mul_6_24_n_37;
   wire mul_6_24_n_38;
   wire mul_6_24_n_39;
   wire mul_6_24_n_40;
   wire mul_6_24_n_41;
   wire mul_6_24_n_42;
   wire mul_6_24_n_43;
   wire mul_6_24_n_44;
   wire mul_6_24_n_45;
   wire mul_6_24_n_46;
   wire mul_6_24_n_47;
   wire mul_6_24_n_48;
   wire mul_6_24_n_49;
   wire mul_6_24_n_50;
   wire mul_6_24_n_51;
   wire mul_6_24_n_52;
   wire mul_6_24_n_53;
   wire mul_6_24_n_54;
   wire mul_6_24_n_55;
   wire mul_6_24_n_56;
   wire mul_6_24_n_57;
   wire mul_6_24_n_58;
   wire mul_6_24_n_59;
   wire mul_6_24_n_60;
   wire mul_6_24_n_61;
   wire mul_6_24_n_62;
   wire mul_6_24_n_63;
   wire mul_6_24_n_64;
   wire mul_6_24_n_65;
   wire mul_6_24_n_66;
   wire mul_6_24_n_67;
   wire mul_6_24_n_68;
   wire mul_6_24_n_69;
   wire mul_6_24_n_70;
   wire mul_6_24_n_71;
   wire mul_6_24_n_73;
   wire mul_6_24_n_74;
   wire mul_6_24_n_75;
   wire mul_6_24_n_76;
   wire mul_6_24_n_77;
   wire mul_6_24_n_78;
   wire mul_6_24_n_79;
   wire mul_6_24_n_80;
   wire mul_6_24_n_81;
   wire mul_6_24_n_82;
   wire mul_6_24_n_83;
   wire mul_6_24_n_84;
   wire mul_6_24_n_85;
   wire mul_6_24_n_86;
   wire mul_6_24_n_87;
   wire mul_6_24_n_89;
   wire mul_6_24_n_90;
   wire mul_6_24_n_91;
   wire mul_6_24_n_92;
   wire mul_6_24_n_93;
   wire mul_6_24_n_94;
   wire mul_6_24_n_96;
   wire mul_6_24_n_98;
   wire mul_6_24_n_100;
   wire mul_6_24_n_104;
   wire mul_6_24_n_106;
   wire mul_6_24_n_110;
   wire mul_6_24_n_112;
   wire mul_6_24_n_114;
   wire mul_6_24_n_116;
   wire mul_6_24_n_118;
   wire mul_6_24_n_122;
   wire mul_6_24_n_123;
   wire mul_6_24_n_124;
   wire mul_6_24_n_125;
   wire mul_6_24_n_126;
   wire mul_6_24_n_127;
   wire mul_6_24_n_128;
   wire mul_6_24_n_129;
   wire mul_6_24_n_130;
   wire mul_6_24_n_131;
   wire mul_6_24_n_132;
   wire mul_6_24_n_133;
   wire mul_6_24_n_134;
   wire mul_6_24_n_135;
   wire mul_6_24_n_136;
   wire mul_6_24_n_137;
   wire mul_6_24_n_138;
   wire mul_6_24_n_139;
   wire mul_6_24_n_140;
   wire mul_6_24_n_141;
   wire mul_6_24_n_142;
   wire mul_6_24_n_143;
   wire mul_6_24_n_144;
   wire mul_6_24_n_145;
   wire mul_6_24_n_146;
   wire mul_6_24_n_147;
   wire mul_6_24_n_148;
   wire mul_6_24_n_149;
   wire mul_6_24_n_150;
   wire mul_6_24_n_151;
   wire mul_6_24_n_152;
   wire mul_6_24_n_153;
   wire mul_6_24_n_154;
   wire mul_6_24_n_155;
   wire mul_6_24_n_156;
   wire mul_6_24_n_157;
   wire mul_6_24_n_158;
   wire mul_6_24_n_159;
   wire mul_6_24_n_160;
   wire mul_6_24_n_161;
   wire mul_6_24_n_162;
   wire mul_6_24_n_163;
   wire mul_6_24_n_164;
   wire mul_6_24_n_165;
   wire mul_6_24_n_166;
   wire mul_6_24_n_167;
   wire mul_6_24_n_168;
   wire mul_6_24_n_169;
   wire mul_6_24_n_170;
   wire mul_6_24_n_171;
   wire mul_6_24_n_172;
   wire mul_6_24_n_173;
   wire mul_6_24_n_174;
   wire mul_6_24_n_175;
   wire mul_6_24_n_177;
   wire mul_6_24_n_178;
   wire mul_6_24_n_179;
   wire mul_6_24_n_180;
   wire mul_6_24_n_181;
   wire mul_6_24_n_182;
   wire mul_6_24_n_183;
   wire mul_6_24_n_184;
   wire mul_6_24_n_185;
   wire mul_6_24_n_187;
   wire mul_6_24_n_188;
   wire mul_6_24_n_191;
   wire mul_6_24_n_192;
   wire mul_6_24_n_193;
   wire mul_6_24_n_194;
   wire mul_6_24_n_195;
   wire n_213;
   wire n_215;
   wire n_216;
   wire n_218;

   CMPE42D1 mul_6_24_cdnca_004_0__2346 (.A(mul_6_24_n_68),
	.B(mul_6_24_n_33),
	.C(mul_6_24_n_61),
	.CIX(mul_6_24_n_82),
	.CO(mul_6_24_n_173),
	.COX(mul_6_24_n_171),
	.D(mul_6_24_n_79),
	.S(mul_6_24_n_122));
   CMPE42D1 mul_6_24_cdnca_005_0__1666 (.A(mul_6_24_n_64),
	.B(mul_6_24_n_68),
	.C(mul_6_24_n_62),
	.CIX(mul_6_24_n_50),
	.CO(mul_6_24_n_170),
	.COX(mul_6_24_n_169),
	.D(mul_6_24_n_84),
	.S(mul_6_24_n_168));
   CMPE42D1 mul_6_24_cdnca_006_0__7410 (.A(mul_6_24_n_66),
	.B(mul_6_24_n_64),
	.C(mul_6_24_n_25),
	.CIX(mul_6_24_n_27),
	.CO(mul_6_24_n_167),
	.COX(mul_6_24_n_166),
	.D(mul_6_24_n_23),
	.S(mul_6_24_n_165));
   CMPE42D1 mul_6_24_cdnca_006_1__6417 (.A(mul_6_24_n_83),
	.B(mul_6_24_n_76),
	.C(mul_6_24_n_165),
	.CIX(mul_6_24_n_169),
	.CO(mul_6_24_n_175),
	.COX(mul_6_24_n_146),
	.D(mul_6_24_n_170),
	.S(mul_6_24_n_185));
   CMPE42D1 mul_6_24_cdnca_007_0__5477 (.A(mul_6_24_n_65),
	.B(mul_6_24_n_21),
	.C(mul_6_24_n_66),
	.CIX(mul_6_24_n_12),
	.CO(mul_6_24_n_164),
	.COX(mul_6_24_n_163),
	.D(mul_6_24_n_58),
	.S(mul_6_24_n_162));
   CMPE42D1 mul_6_24_cdnca_007_1__2398 (.A(mul_6_24_n_18),
	.B(mul_6_24_n_75),
	.C(mul_6_24_n_74),
	.CIX(mul_6_24_n_162),
	.CO(mul_6_24_n_145),
	.COX(mul_6_24_n_144),
	.D(mul_6_24_n_166),
	.S(mul_6_24_n_143));
   CMPE42D1 mul_6_24_cdnca_008_0__5107 (.A(mul_6_24_n_20),
	.B(mul_6_24_n_15),
	.C(mul_6_24_n_69),
	.CIX(mul_6_24_n_47),
	.CO(mul_6_24_n_161),
	.COX(mul_6_24_n_160),
	.D(mul_6_24_n_65),
	.S(mul_6_24_n_159));
   CMPE42D1 mul_6_24_cdnca_008_1__6260 (.A(mul_6_24_n_51),
	.B(mul_6_24_n_44),
	.C(mul_6_24_n_11),
	.CIX(mul_6_24_n_73),
	.CO(mul_6_24_n_142),
	.COX(mul_6_24_n_141),
	.D(mul_6_24_n_159),
	.S(mul_6_24_n_140));
   CMPE42D1 mul_6_24_cdnca_008_2__4319 (.A(mul_6_24_n_163),
	.B(mul_6_24_n_164),
	.C(mul_6_24_n_140),
	.CIX(mul_6_24_n_144),
	.CO(mul_6_24_n_177),
	.COX(mul_6_24_n_130),
	.D(mul_6_24_n_145),
	.S(mul_6_24_n_187));
   CMPE42D1 mul_6_24_cdnca_009_0__8428 (.A(mul_6_24_n_49),
	.B(mul_6_24_n_53),
	.C(mul_6_24_n_63),
	.CIX(mul_6_24_n_57),
	.CO(mul_6_24_n_158),
	.COX(mul_6_24_n_157),
	.D(mul_6_24_n_69),
	.S(mul_6_24_n_156));
   CMPE42D1 mul_6_24_cdnca_009_1__5526 (.A(mul_6_24_n_46),
	.B(mul_6_24_n_17),
	.C(mul_6_24_n_41),
	.CIX(mul_6_24_n_156),
	.CO(mul_6_24_n_139),
	.COX(mul_6_24_n_138),
	.D(mul_6_24_n_160),
	.S(mul_6_24_n_137));
   CMPE42D1 mul_6_24_cdnca_009_2__6783 (.A(mul_6_24_n_161),
	.B(mul_6_24_n_141),
	.C(mul_6_24_n_137),
	.CIX(mul_6_24_n_142),
	.CO(mul_6_24_n_178),
	.COX(mul_6_24_n_124),
	.D(mul_6_24_n_130),
	.S(mul_6_24_n_188));
   CMPE42D1 mul_6_24_cdnca_010_0__3680 (.A(mul_6_24_n_63),
	.B(mul_6_24_n_19),
	.C(mul_6_24_n_30),
	.CIX(mul_6_24_n_16),
	.CO(mul_6_24_n_155),
	.COX(mul_6_24_n_154),
	.D(mul_6_24_n_40),
	.S(mul_6_24_n_153));
   CMPE42D1 mul_6_24_cdnca_010_1__1617 (.A(mul_6_24_n_78),
	.B(mul_6_24_n_153),
	.C(mul_6_24_n_157),
	.CIX(mul_6_24_n_158),
	.CO(mul_6_24_n_129),
	.COX(mul_6_24_n_128),
	.D(mul_6_24_n_138),
	.S(mul_6_24_n_127));
   CMPE42D1 mul_6_24_cdnca_011_0__2802 (.A(mul_6_24_n_43),
	.B(mul_6_24_n_32),
	.C(mul_6_24_n_56),
	.CIX(mul_6_24_n_60),
	.CO(mul_6_24_n_152),
	.COX(mul_6_24_n_151),
	.D(mul_6_24_n_30),
	.S(mul_6_24_n_150));
   CMPE42D1 mul_6_24_cdnca_011_1__1705 (.A(mul_6_24_n_42),
	.B(mul_6_24_n_77),
	.C(mul_6_24_n_150),
	.CIX(mul_6_24_n_154),
	.CO(mul_6_24_n_136),
	.COX(mul_6_24_n_135),
	.D(mul_6_24_n_155),
	.S(mul_6_24_n_134));
   CMPE42D1 mul_6_24_cdnca_012_0__5122 (.A(mul_6_24_n_31),
	.B(mul_6_24_n_32),
	.C(mul_6_24_n_52),
	.CIX(mul_6_24_n_54),
	.CO(mul_6_24_n_149),
	.COX(mul_6_24_n_148),
	.D(mul_6_24_n_59),
	.S(mul_6_24_n_147));
   CMPE42D1 mul_6_24_cdnca_012_1__8246 (.A(mul_6_24_n_147),
	.B(mul_6_24_n_151),
	.C(mul_6_24_n_152),
	.CIX(mul_6_24_n_135),
	.CO(mul_6_24_n_181),
	.COX(mul_6_24_n_126),
	.D(mul_6_24_n_136),
	.S(mul_6_24_n_180));
   CMPE42D1 mul_6_24_cdnca_013_0__7098 (.A(mul_6_24_n_31),
	.B(mul_6_24_n_55),
	.C(mul_6_24_n_22),
	.CIX(mul_6_24_n_48),
	.CO(mul_6_24_n_133),
	.COX(mul_6_24_n_132),
	.D(mul_6_24_n_148),
	.S(mul_6_24_n_131));
   CMPE42D1 mul_6_24_cdnca_014_0__6131 (.A(mul_6_24_n_14),
	.B(mul_6_24_n_45),
	.C(mul_6_24_n_9),
	.CIX(mul_6_24_n_132),
	.CO(mul_6_24_n_183),
	.COX(mul_6_24_n_125),
	.D(mul_6_24_n_133),
	.S(mul_6_24_n_182));
   FA1D0 mul_6_24_cdnfadd_003_0__1881 (.A(mul_6_24_n_33),
	.B(mul_6_24_n_13),
	.CI(mul_6_24_n_80),
	.CO(mul_6_24_n_172),
	.S(mul_6_24_n_123));
   FA1D0 mul_6_24_cdnfadd_005_1__5115 (.A(mul_6_24_n_81),
	.B(mul_6_24_n_168),
	.CI(mul_6_24_n_171),
	.CO(mul_6_24_n_174),
	.S(mul_6_24_n_184));
   FA1D0 mul_6_24_cdnfadd_011_2__6161 (.A(mul_6_24_n_134),
	.B(mul_6_24_n_128),
	.CI(mul_6_24_n_129),
	.CO(mul_6_24_n_191),
	.S(mul_6_24_n_179));
   FA1D0 mul_6_24_cdnfadd_013_1__9315 (.A(mul_6_24_n_149),
	.B(mul_6_24_n_131),
	.CI(mul_6_24_n_126),
	.CO(mul_6_24_n_193),
	.S(mul_6_24_n_192));
   FA1D0 mul_6_24_cdnfadd_015_0__9945 (.A(mul_6_24_n_10),
	.B(mul_6_24_n_24),
	.CI(mul_6_24_n_125),
	.CO(mul_6_24_n_195),
	.S(mul_6_24_n_194));
   FA1D0 mul_6_24_g982__2883 (.A(mul_6_24_n_195),
	.B(mul_6_24_n_0),
	.CI(mul_6_24_n_118),
	.CO(product[17]),
	.S(product[16]));
   FA1D0 mul_6_24_g983__2346 (.A(mul_6_24_n_183),
	.B(mul_6_24_n_194),
	.CI(mul_6_24_n_116),
	.CO(mul_6_24_n_118),
	.S(product[15]));
   FA1D0 mul_6_24_g984__1666 (.A(mul_6_24_n_193),
	.B(mul_6_24_n_182),
	.CI(mul_6_24_n_114),
	.CO(mul_6_24_n_116),
	.S(product[14]));
   FA1D0 mul_6_24_g985__7410 (.A(mul_6_24_n_181),
	.B(mul_6_24_n_192),
	.CI(mul_6_24_n_112),
	.CO(mul_6_24_n_114),
	.S(product[13]));
   FA1D0 mul_6_24_g986__6417 (.A(mul_6_24_n_180),
	.B(mul_6_24_n_191),
	.CI(mul_6_24_n_110),
	.CO(mul_6_24_n_112),
	.S(product[12]));
   FA1D0 mul_6_24_g987__5477 (.A(n_215),
	.B(mul_6_24_n_179),
	.CI(n_213),
	.CO(mul_6_24_n_110),
	.S(product[11]));
   FA1D0 mul_6_24_g989__5107 (.A(mul_6_24_n_188),
	.B(mul_6_24_n_177),
	.CI(mul_6_24_n_104),
	.CO(mul_6_24_n_106),
	.S(product[9]));
   FA1D0 mul_6_24_g990__6260 (.A(n_216),
	.B(n_218),
	.CI(mul_6_24_n_187),
	.CO(mul_6_24_n_104),
	.S(product[8]));
   FA1D0 mul_6_24_g992__8428 (.A(mul_6_24_n_185),
	.B(mul_6_24_n_174),
	.CI(mul_6_24_n_98),
	.CO(mul_6_24_n_100),
	.S(product[6]));
   FA1D0 mul_6_24_g993__5526 (.A(mul_6_24_n_96),
	.B(mul_6_24_n_173),
	.CI(mul_6_24_n_184),
	.CO(mul_6_24_n_98),
	.S(product[5]));
   FA1D0 mul_6_24_g994__6783 (.A(mul_6_24_n_93),
	.B(mul_6_24_n_172),
	.CI(mul_6_24_n_122),
	.CO(mul_6_24_n_96),
	.S(product[4]));
   XNR2D1 mul_6_24_g995__3680 (.A1(mul_6_24_n_94),
	.A2(mul_6_24_n_87),
	.ZN(product[3]));
   NR2XD0 mul_6_24_g996__1617 (.A1(mul_6_24_n_91),
	.A2(mul_6_24_n_90),
	.ZN(mul_6_24_n_94));
   OAI21D1 mul_6_24_g997__2802 (.A1(mul_6_24_n_90),
	.A2(mul_6_24_n_87),
	.B(mul_6_24_n_92),
	.ZN(mul_6_24_n_93));
   INVD1 mul_6_24_g998 (.I(mul_6_24_n_91),
	.ZN(mul_6_24_n_92));
   NR3D0 mul_6_24_g999__1705 (.A1(mul_6_24_n_89),
	.A2(mul_6_24_n_29),
	.A3(mul_6_24_n_28),
	.ZN(mul_6_24_n_91));
   OA21D1 mul_6_24_g1000__5122 (.A1(mul_6_24_n_29),
	.A2(mul_6_24_n_28),
	.B(mul_6_24_n_89),
	.Z(mul_6_24_n_90));
   INVD1 mul_6_24_g1001 (.I(mul_6_24_n_123),
	.ZN(mul_6_24_n_89));
   CKXOR2D1 mul_6_24_g1002__8246 (.A1(mul_6_24_n_86),
	.A2(mul_6_24_n_70),
	.Z(product[2]));
   NR2XD0 mul_6_24_g1003__7098 (.A1(mul_6_24_n_85),
	.A2(mul_6_24_n_70),
	.ZN(mul_6_24_n_87));
   HA1D0 mul_6_24_g1004__6131 (.A(mul_6_24_n_8),
	.B(mul_6_24_n_71),
	.CO(mul_6_24_n_85),
	.S(mul_6_24_n_86));
   HA1D0 mul_6_24_g1005__1881 (.A(mul_6_24_n_2),
	.B(mul_6_24_n_3),
	.CO(mul_6_24_n_83),
	.S(mul_6_24_n_84));
   HA1D0 mul_6_24_g1006__5115 (.A(mul_6_24_n_36),
	.B(mul_6_24_n_7),
	.CO(mul_6_24_n_81),
	.S(mul_6_24_n_82));
   HA1D0 mul_6_24_g1007__7482 (.A(mul_6_24_n_37),
	.B(mul_6_24_n_5),
	.CO(mul_6_24_n_79),
	.S(mul_6_24_n_80));
   HA1D0 mul_6_24_g1008__4733 (.A(mul_6_24_n_1),
	.B(mul_6_24_n_39),
	.CO(mul_6_24_n_77),
	.S(mul_6_24_n_78));
   HA1D0 mul_6_24_g1009__6161 (.A(mul_6_24_n_4),
	.B(mul_6_24_n_35),
	.CO(mul_6_24_n_75),
	.S(mul_6_24_n_76));
   HA1D0 mul_6_24_g1010__9315 (.A(mul_6_24_n_38),
	.B(mul_6_24_n_6),
	.CO(mul_6_24_n_73),
	.S(mul_6_24_n_74));
   AOI21D1 mul_6_24_g1011__9945 (.A1(mul_6_24_n_67),
	.A2(mul_6_24_n_34),
	.B(mul_6_24_n_70),
	.ZN(product[1]));
   CKXOR2D1 mul_6_24_g1012__2883 (.A1(mul_6_24_n_28),
	.A2(mul_6_24_n_29),
	.Z(mul_6_24_n_71));
   NR2XD0 mul_6_24_g1013__2346 (.A1(mul_6_24_n_67),
	.A2(mul_6_24_n_34),
	.ZN(mul_6_24_n_70));
   AN2XD1 mul_6_24_g1014__1666 (.A1(a[3]),
	.A2(b[2]),
	.Z(mul_6_24_n_62));
   AN2XD1 mul_6_24_g1015__7410 (.A1(a[2]),
	.A2(b[2]),
	.Z(mul_6_24_n_61));
   AN2XD1 mul_6_24_g1016__6417 (.A1(a[5]),
	.A2(b[6]),
	.Z(mul_6_24_n_60));
   AN2XD1 mul_6_24_g1017__5477 (.A1(a[7]),
	.A2(b[5]),
	.Z(mul_6_24_n_59));
   AN2XD1 mul_6_24_g1018__2398 (.A1(a[2]),
	.A2(b[5]),
	.Z(mul_6_24_n_58));
   AN2XD1 mul_6_24_g1019__5107 (.A1(a[2]),
	.A2(b[7]),
	.Z(mul_6_24_n_57));
   AN2XD1 mul_6_24_g1020__6260 (.A1(a[6]),
	.A2(b[5]),
	.Z(mul_6_24_n_56));
   AN2XD1 mul_6_24_g1021__4319 (.A1(a[8]),
	.A2(b[5]),
	.Z(mul_6_24_n_55));
   AN2XD1 mul_6_24_g1022__8428 (.A1(a[5]),
	.A2(b[7]),
	.Z(mul_6_24_n_54));
   AN2XD1 mul_6_24_g1023__5526 (.A1(a[8]),
	.A2(b[1]),
	.Z(mul_6_24_n_53));
   AN2XD1 mul_6_24_g1024__6783 (.A1(a[6]),
	.A2(b[6]),
	.Z(mul_6_24_n_52));
   AN2XD1 mul_6_24_g1025__3680 (.A1(a[6]),
	.A2(b[2]),
	.Z(mul_6_24_n_51));
   AN2XD1 mul_6_24_g1026__1617 (.A1(a[0]),
	.A2(b[5]),
	.Z(mul_6_24_n_50));
   AN2XD1 mul_6_24_g1027__2802 (.A1(a[9]),
	.A2(b[0]),
	.Z(mul_6_24_n_49));
   AN2XD1 mul_6_24_g1028__1705 (.A1(a[7]),
	.A2(b[6]),
	.Z(mul_6_24_n_48));
   AN2XD1 mul_6_24_g1029__5122 (.A1(a[1]),
	.A2(b[7]),
	.Z(mul_6_24_n_47));
   AN2XD1 mul_6_24_g1030__8246 (.A1(a[7]),
	.A2(b[2]),
	.Z(mul_6_24_n_46));
   AN2XD1 mul_6_24_g1031__7098 (.A1(a[8]),
	.A2(b[6]),
	.Z(mul_6_24_n_45));
   AN2XD1 mul_6_24_g1032__6131 (.A1(a[3]),
	.A2(b[5]),
	.Z(mul_6_24_n_44));
   AN2XD1 mul_6_24_g1033__1881 (.A1(a[9]),
	.A2(b[2]),
	.Z(mul_6_24_n_43));
   AN2XD1 mul_6_24_g1034__5115 (.A1(a[4]),
	.A2(b[7]),
	.Z(mul_6_24_n_42));
   AN2XD1 mul_6_24_g1035__7482 (.A1(a[3]),
	.A2(b[6]),
	.Z(mul_6_24_n_41));
   AN2XD1 mul_6_24_g1036__4733 (.A1(a[3]),
	.A2(b[7]),
	.Z(mul_6_24_n_40));
   AN2XD1 mul_6_24_g1037__6161 (.A1(a[9]),
	.A2(b[1]),
	.Z(mul_6_24_n_39));
   AN2XD1 mul_6_24_g1038__9315 (.A1(a[5]),
	.A2(b[3]),
	.Z(mul_6_24_n_69));
   AN2XD1 mul_6_24_g1039__9945 (.A1(a[1]),
	.A2(b[3]),
	.Z(mul_6_24_n_68));
   CKND2D1 mul_6_24_g1040__2883 (.A1(a[1]),
	.A2(b[0]),
	.ZN(mul_6_24_n_67));
   AN2XD1 mul_6_24_g1041__2346 (.A1(a[6]),
	.A2(b[1]),
	.Z(mul_6_24_n_38));
   AN2XD1 mul_6_24_g1042__1666 (.A1(a[3]),
	.A2(b[3]),
	.Z(mul_6_24_n_66));
   AN2XD1 mul_6_24_g1043__7410 (.A1(a[2]),
	.A2(b[1]),
	.Z(mul_6_24_n_37));
   AN2XD1 mul_6_24_g1044__6417 (.A1(a[4]),
	.A2(b[3]),
	.Z(mul_6_24_n_65));
   AN2XD1 mul_6_24_g1045__5477 (.A1(a[3]),
	.A2(b[1]),
	.Z(mul_6_24_n_36));
   AN2XD1 mul_6_24_g1046__2398 (.A1(a[6]),
	.A2(b[0]),
	.Z(mul_6_24_n_35));
   AN2XD1 mul_6_24_g1047__5107 (.A1(a[2]),
	.A2(b[3]),
	.Z(mul_6_24_n_64));
   AN2XD1 mul_6_24_g1048__6260 (.A1(a[6]),
	.A2(b[3]),
	.Z(mul_6_24_n_63));
   AN2XD1 mul_6_24_g1049__4319 (.A1(a[1]),
	.A2(b[5]),
	.Z(mul_6_24_n_27));
   AN2XD1 mul_6_24_g1050__8428 (.A1(a[0]),
	.A2(b[0]),
	.Z(product[0]));
   AN2XD1 mul_6_24_g1051__5526 (.A1(a[4]),
	.A2(b[2]),
	.Z(mul_6_24_n_25));
   AN2XD1 mul_6_24_g1052__6783 (.A1(a[8]),
	.A2(b[7]),
	.Z(mul_6_24_n_24));
   AN2XD1 mul_6_24_g1053__3680 (.A1(a[0]),
	.A2(b[6]),
	.Z(mul_6_24_n_23));
   AN2XD1 mul_6_24_g1054__1617 (.A1(a[6]),
	.A2(b[7]),
	.Z(mul_6_24_n_22));
   AN2XD1 mul_6_24_g1055__2802 (.A1(a[0]),
	.A2(b[7]),
	.Z(mul_6_24_n_21));
   AN2XD1 mul_6_24_g1056__1705 (.A1(a[8]),
	.A2(b[0]),
	.Z(mul_6_24_n_20));
   AN2XD1 mul_6_24_g1057__5122 (.A1(a[5]),
	.A2(b[5]),
	.Z(mul_6_24_n_19));
   AN2XD1 mul_6_24_g1058__8246 (.A1(a[1]),
	.A2(b[6]),
	.Z(mul_6_24_n_18));
   AN2XD1 mul_6_24_g1059__7098 (.A1(a[4]),
	.A2(b[5]),
	.Z(mul_6_24_n_17));
   AN2XD1 mul_6_24_g1060__6131 (.A1(a[4]),
	.A2(b[6]),
	.Z(mul_6_24_n_16));
   AN2XD1 mul_6_24_g1061__1881 (.A1(a[7]),
	.A2(b[1]),
	.Z(mul_6_24_n_15));
   AN2XD1 mul_6_24_g1062__5115 (.A1(a[9]),
	.A2(b[5]),
	.Z(mul_6_24_n_14));
   AN2XD1 mul_6_24_g1063__7482 (.A1(a[1]),
	.A2(b[2]),
	.Z(mul_6_24_n_13));
   AN2XD1 mul_6_24_g1064__4733 (.A1(a[5]),
	.A2(b[2]),
	.Z(mul_6_24_n_12));
   AN2XD1 mul_6_24_g1065__6161 (.A1(a[2]),
	.A2(b[6]),
	.Z(mul_6_24_n_11));
   AN2XD1 mul_6_24_g1066__9315 (.A1(a[9]),
	.A2(b[6]),
	.Z(mul_6_24_n_10));
   AN2XD1 mul_6_24_g1067__9945 (.A1(a[7]),
	.A2(b[7]),
	.Z(mul_6_24_n_9));
   AN2XD1 mul_6_24_g1068__2883 (.A1(a[1]),
	.A2(b[1]),
	.Z(mul_6_24_n_8));
   CKND2D1 mul_6_24_g1069__2346 (.A1(a[0]),
	.A2(b[1]),
	.ZN(mul_6_24_n_34));
   AN2XD1 mul_6_24_g1070__1666 (.A1(a[4]),
	.A2(b[0]),
	.Z(mul_6_24_n_7));
   AN2XD1 mul_6_24_g1071__7410 (.A1(a[7]),
	.A2(b[0]),
	.Z(mul_6_24_n_6));
   AN2XD1 mul_6_24_g1072__6417 (.A1(a[3]),
	.A2(b[0]),
	.Z(mul_6_24_n_5));
   AN2XD1 mul_6_24_g1073__5477 (.A1(a[5]),
	.A2(b[1]),
	.Z(mul_6_24_n_4));
   AN2XD1 mul_6_24_g1074__2398 (.A1(a[0]),
	.A2(b[3]),
	.Z(mul_6_24_n_33));
   AN2XD1 mul_6_24_g1075__5107 (.A1(a[5]),
	.A2(b[0]),
	.Z(mul_6_24_n_3));
   AN2XD1 mul_6_24_g1076__6260 (.A1(a[4]),
	.A2(b[1]),
	.Z(mul_6_24_n_2));
   AN2XD1 mul_6_24_g1077__4319 (.A1(a[8]),
	.A2(b[3]),
	.Z(mul_6_24_n_32));
   AN2XD1 mul_6_24_g1078__8428 (.A1(a[8]),
	.A2(b[2]),
	.Z(mul_6_24_n_1));
   AN2XD1 mul_6_24_g1079__5526 (.A1(a[9]),
	.A2(b[3]),
	.Z(mul_6_24_n_31));
   AN2XD1 mul_6_24_g1080__6783 (.A1(a[9]),
	.A2(b[7]),
	.Z(mul_6_24_n_0));
   AN2XD1 mul_6_24_g1081__3680 (.A1(a[7]),
	.A2(b[3]),
	.Z(mul_6_24_n_30));
   ND2D1 mul_6_24_g1082__1617 (.A1(a[0]),
	.A2(b[2]),
	.ZN(mul_6_24_n_29));
   ND2D1 mul_6_24_g1083__2802 (.A1(a[2]),
	.A2(b[0]),
	.ZN(mul_6_24_n_28));
   CMPE42D1 g2 (.A(mul_6_24_n_139),
	.B(mul_6_24_n_127),
	.C(mul_6_24_n_124),
	.CIX(mul_6_24_n_178),
	.CO(n_213),
	.COX(n_215),
	.D(mul_6_24_n_106),
	.S(product[10]));
   CMPE42D1 g1084 (.A(mul_6_24_n_167),
	.B(mul_6_24_n_143),
	.C(mul_6_24_n_146),
	.CIX(mul_6_24_n_175),
	.CO(n_216),
	.COX(n_218),
	.D(mul_6_24_n_100),
	.S(product[7]));
endmodule

module class1_top_channels (
	clk, 
	rst, 
	channel, 
	channel_weight);
   input clk;
   input rst;
   input [7:0] channel;
   output [7:0] channel_weight;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;

   DFQD1 \channel_weight_reg[3]  (.CP(clk),
	.D(n_24),
	.Q(channel_weight[4]));
   DFQD1 \channel_weight_reg[0]  (.CP(clk),
	.D(n_20),
	.Q(channel_weight[0]));
   CKND2D0 g3028__1705 (.A1(n_15),
	.A2(n_23),
	.ZN(n_24));
   DFQD1 \channel_weight_reg[7]  (.CP(clk),
	.D(n_22),
	.Q(channel_weight[7]));
   DFQD1 \channel_weight_reg[5]  (.CP(clk),
	.D(n_19),
	.Q(channel_weight[5]));
   SDFKCNQD0 \channel_weight_reg[1]  (.CN(n_8),
	.CP(clk),
	.D(n_5),
	.Q(channel_weight[1]),
	.SE(n_16),
	.SI(channel_weight[1]));
   EDFQD1 \channel_weight_reg[2]  (.CP(clk),
	.D(n_12),
	.E(n_17),
	.Q(channel_weight[2]));
   AOI211D0 g3033__5122 (.A1(n_16),
	.A2(channel_weight[4]),
	.B(n_13),
	.C(n_14),
	.ZN(n_23));
   CKND2D0 g3034__8246 (.A1(n_15),
	.A2(n_18),
	.ZN(n_22));
   OAI211D0 g3035__7098 (.A1(n_0),
	.A2(n_17),
	.B(n_9),
	.C(n_15),
	.ZN(n_21));
   AO211D0 g3036__6131 (.A1(n_16),
	.A2(channel_weight[0]),
	.B(n_11),
	.C(n_13),
	.Z(n_20));
   AO21D0 g3037__1881 (.A1(n_16),
	.A2(channel_weight[5]),
	.B(n_14),
	.Z(n_19));
   AOI21D0 g3038__5115 (.A1(n_16),
	.A2(channel_weight[7]),
	.B(n_11),
	.ZN(n_18));
   INVD1 g3039 (.I(n_17),
	.ZN(n_16));
   IND4D0 g3040__7482 (.A1(n_14),
	.B1(n_9),
	.B2(n_5),
	.B3(n_15),
	.ZN(n_17));
   IND4D0 g3041__4733 (.A1(n_10),
	.B1(channel[3]),
	.B2(channel[1]),
	.B3(channel[2]),
	.ZN(n_15));
   IND2D0 g3042__6161 (.A1(n_11),
	.B1(n_8),
	.ZN(n_14));
   INR2D0 g3043__9315 (.A1(n_9),
	.B1(rst),
	.ZN(n_12));
   OAI21D0 g3044__9945 (.A1(n_4),
	.A2(rst),
	.B(n_9),
	.ZN(n_13));
   IND3D0 g3045__2883 (.A1(n_7),
	.B1(channel[0]),
	.B2(channel[4]),
	.ZN(n_10));
   INR3D0 g3046__2346 (.A1(n_2),
	.B1(n_7),
	.B2(channel[4]),
	.ZN(n_11));
   CKND2D0 g3047__1666 (.A1(n_5),
	.A2(n_6),
	.ZN(n_9));
   ND3D0 g3048__7410 (.A1(n_2),
	.A2(n_5),
	.A3(n_1),
	.ZN(n_8));
   INR4D0 g3049__6417 (.A1(n_3),
	.B1(channel[3]),
	.B2(channel[2]),
	.B3(channel[1]),
	.ZN(n_6));
   IND4D0 g3050__5477 (.A1(channel[5]),
	.B1(channel[6]),
	.B2(n_5),
	.B3(channel[7]),
	.ZN(n_7));
   INR2D0 g3051__2398 (.A1(n_4),
	.B1(rst),
	.ZN(n_5));
   CKND2D0 g3052__5107 (.A1(n_3),
	.A2(n_2),
	.ZN(n_4));
   INR2D0 g3053__6260 (.A1(n_1),
	.B1(channel[4]),
	.ZN(n_3));
   NR4D0 g3054__4319 (.A1(channel[3]),
	.A2(channel[2]),
	.A3(channel[1]),
	.A4(channel[0]),
	.ZN(n_2));
   NR3D0 g3055__8428 (.A1(channel[6]),
	.A2(channel[7]),
	.A3(channel[5]),
	.ZN(n_1));
   DFD1 \channel_weight_reg[6]  (.CP(clk),
	.D(n_21),
	.Q(channel_weight[6]),
	.QN(n_0));
endmodule

module class2_top_channels (
	clk, 
	rst, 
	channel, 
	channel_weight);
   input clk;
   input rst;
   input [7:0] channel;
   output [7:0] channel_weight;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;

   DFQD1 \channel_weight_reg[3]  (.CP(clk),
	.D(n_31),
	.Q(channel_weight[4]));
   DFQD1 \channel_weight_reg[1]  (.CP(clk),
	.D(n_29),
	.Q(channel_weight[1]));
   DFQD1 \channel_weight_reg[5]  (.CP(clk),
	.D(n_27),
	.Q(channel_weight[5]));
   CKND2D0 g3152__5526 (.A1(n_21),
	.A2(n_30),
	.ZN(n_31));
   DFQD1 \channel_weight_reg[7]  (.CP(clk),
	.D(n_26),
	.Q(channel_weight[7]));
   DFQD1 \channel_weight_reg[0]  (.CP(clk),
	.D(n_25),
	.Q(channel_weight[0]));
   EDFQD1 \channel_weight_reg[2]  (.CP(clk),
	.D(n_17),
	.E(n_23),
	.Q(channel_weight[2]));
   AOI211D0 g3157__6783 (.A1(n_24),
	.A2(channel_weight[4]),
	.B(n_15),
	.C(n_20),
	.ZN(n_30));
   AO211D0 g3158__3680 (.A1(n_24),
	.A2(channel_weight[1]),
	.B(n_22),
	.C(n_14),
	.Z(n_29));
   OAI211D0 g3159__1617 (.A1(n_1),
	.A2(n_23),
	.B(n_13),
	.C(n_21),
	.ZN(n_28));
   AO211D0 g3160__2802 (.A1(n_24),
	.A2(channel_weight[5]),
	.B(n_19),
	.C(n_15),
	.Z(n_27));
   AO21D0 g3161__1705 (.A1(n_24),
	.A2(channel_weight[7]),
	.B(n_22),
	.Z(n_26));
   AO21D0 g3162__5122 (.A1(n_24),
	.A2(channel_weight[0]),
	.B(n_20),
	.Z(n_25));
   INVD1 g3163 (.I(n_24),
	.ZN(n_23));
   NR2D0 g3164__8246 (.A1(n_22),
	.A2(n_16),
	.ZN(n_24));
   IND2D0 g3165__7098 (.A1(n_19),
	.B1(n_21),
	.ZN(n_22));
   IND4D0 g3166__6131 (.A1(n_18),
	.B1(channel[1]),
	.B2(channel[0]),
	.B3(n_2),
	.ZN(n_21));
   AO211D0 g3167__1881 (.A1(n_9),
	.A2(n_0),
	.B(n_19),
	.C(n_14),
	.Z(n_20));
   NR2D0 g3168__5115 (.A1(n_7),
	.A2(n_18),
	.ZN(n_19));
   IIND4D0 g3169__7482 (.A1(channel[5]),
	.A2(n_16),
	.B1(channel[6]),
	.B2(channel[7]),
	.ZN(n_18));
   NR3D0 g3170__4733 (.A1(n_8),
	.A2(n_14),
	.A3(rst),
	.ZN(n_17));
   IND4D0 g3171__6161 (.A1(n_8),
	.B1(n_11),
	.B2(n_12),
	.B3(n_10),
	.ZN(n_16));
   INR2D0 g3172__9315 (.A1(n_12),
	.B1(n_10),
	.ZN(n_15));
   INVD1 g3173 (.I(n_13),
	.ZN(n_14));
   IND2D0 g3174__9945 (.A1(n_11),
	.B1(n_12),
	.ZN(n_13));
   NR2D0 g3175__2883 (.A1(n_9),
	.A2(rst),
	.ZN(n_12));
   OR4D0 g3176__2346 (.A1(channel[5]),
	.A2(channel[1]),
	.A3(channel[0]),
	.A4(n_5),
	.Z(n_11));
   IND4D0 g3177__1666 (.A1(channel[1]),
	.B1(channel[5]),
	.B2(channel[0]),
	.B3(n_6),
	.ZN(n_10));
   IINR4D0 g3178__7410 (.A1(n_6),
	.A2(channel[1]),
	.B1(channel[5]),
	.B2(channel[0]),
	.ZN(n_9));
   NR4D0 g3179__6417 (.A1(n_7),
	.A2(channel[5]),
	.A3(channel[7]),
	.A4(channel[6]),
	.ZN(n_8));
   IND2D0 g3180__5477 (.A1(channel[0]),
	.B1(n_3),
	.ZN(n_7));
   CKND2D0 g3181__2398 (.A1(channel[6]),
	.A2(n_4),
	.ZN(n_5));
   INR2D0 g3182__5107 (.A1(n_4),
	.B1(channel[6]),
	.ZN(n_6));
   INR2D0 g3183__6260 (.A1(n_2),
	.B1(channel[7]),
	.ZN(n_4));
   NR4D0 g3184__4319 (.A1(channel[1]),
	.A2(channel[3]),
	.A3(channel[4]),
	.A4(channel[2]),
	.ZN(n_3));
   AN3D1 g3185__8428 (.A1(channel[4]),
	.A2(channel[3]),
	.A3(channel[2]),
	.Z(n_2));
   INVD1 g3187 (.I(rst),
	.ZN(n_0));
   DFD1 \channel_weight_reg[6]  (.CP(clk),
	.D(n_28),
	.Q(channel_weight[6]),
	.QN(n_1));
endmodule

module counter_gen (
	clk, 
	rst, 
	counter_3_out, 
	counter_5_out, 
	clk_4096k, 
	p1);
   input clk;
   input rst;
   output [2:0] counter_3_out;
   output [4:0] counter_5_out;
   output clk_4096k;
   input p1;

   // Internal wires
   wire [4:0] clk_maker_out;
   wire UNCONNECTED;
   wire UNCONNECTED0;
   wire UNCONNECTED1;
   wire UNCONNECTED2;
   wire UNCONNECTED3;
   wire UNCONNECTED4;
   wire UNCONNECTED5;
   wire UNCONNECTED6;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;

   DFKSND1 \u1_counter_5bit_q_reg[2]  (.CP(clk),
	.D(rst),
	.Q(counter_5_out[2]),
	.QN(UNCONNECTED),
	.SN(n_23));
   DFKSND1 \u1_counter_5bit_q_reg[3]  (.CP(clk),
	.D(rst),
	.Q(counter_5_out[3]),
	.QN(UNCONNECTED0),
	.SN(n_22));
   DFKSND1 \u1_counter_5bit_q_reg[4]  (.CP(clk),
	.D(rst),
	.Q(counter_5_out[4]),
	.QN(UNCONNECTED1),
	.SN(n_21));
   EDFKCNQD1 \u1_counter_5bit_q_reg[1]  (.CN(p1),
	.CP(clk),
	.D(n_4),
	.E(n_19),
	.Q(counter_5_out[1]));
   DFKSND1 \u1_counter_5bit_q_reg[0]  (.CP(clk),
	.D(rst),
	.Q(counter_5_out[0]),
	.QN(UNCONNECTED2),
	.SN(n_20));
   MUX2ND0 g281__5526 (.I0(counter_5_out[2]),
	.I1(n_12),
	.S(n_19),
	.ZN(n_23));
   DFKSND1 \u_counter_5bit_q_reg[4]  (.CP(clk),
	.D(n_18),
	.Q(clk_maker_out[4]),
	.QN(UNCONNECTED3),
	.SN(p1));
   MUX2ND0 g283__6783 (.I0(counter_5_out[3]),
	.I1(n_14),
	.S(n_19),
	.ZN(n_22));
   MUX2ND0 g284__3680 (.I0(counter_5_out[4]),
	.I1(n_17),
	.S(n_19),
	.ZN(n_21));
   XNR2D1 g285__1617 (.A1(n_19),
	.A2(counter_5_out[0]),
	.ZN(n_20));
   HA1D0 g286__2802 (.A(clk_maker_out[4]),
	.B(n_15),
	.CO(n_19),
	.S(n_18));
   DFKSND1 \u_counter_5bit_q_reg[3]  (.CP(clk),
	.D(n_16),
	.Q(clk_maker_out[3]),
	.QN(UNCONNECTED4),
	.SN(p1));
   CKXOR2D1 g288__1705 (.A1(n_13),
	.A2(counter_5_out[4]),
	.Z(n_17));
   HA1D0 g289__5122 (.A(clk_maker_out[3]),
	.B(n_9),
	.CO(n_15),
	.S(n_16));
   HA1D0 g290__8246 (.A(counter_5_out[3]),
	.B(n_11),
	.CO(n_13),
	.S(n_14));
   EDFKCNQD1 \u_counter_3bit_q_reg[2]  (.CN(p1),
	.CP(clk),
	.D(n_7),
	.E(n_6),
	.Q(counter_3_out[2]));
   DFKSND1 \u_counter_5bit_q_reg[2]  (.CP(clk),
	.D(n_10),
	.Q(clk_maker_out[2]),
	.QN(UNCONNECTED5),
	.SN(p1));
   DFKCNQD1 \u_counter_3bit_q_reg[0]  (.CN(p1),
	.CP(clk),
	.D(n_8),
	.Q(counter_3_out[0]));
   EDFKCNQD1 \u_counter_3bit_q_reg[1]  (.CN(p1),
	.CP(clk),
	.D(n_2),
	.E(n_6),
	.Q(counter_3_out[1]));
   HA1D0 g295__7098 (.A(counter_5_out[2]),
	.B(n_3),
	.CO(n_11),
	.S(n_12));
   HA1D0 g296__6131 (.A(clk_maker_out[2]),
	.B(n_6),
	.CO(n_9),
	.S(n_10));
   XOR2D1 g298__1881 (.A1(n_6),
	.A2(counter_3_out[0]),
	.Z(n_8));
   CKXOR2D1 g299__5115 (.A1(n_1),
	.A2(counter_3_out[2]),
	.Z(n_7));
   HA1D0 g300__7482 (.A(clk_maker_out[0]),
	.B(clk_maker_out[1]),
	.CO(n_6),
	.S(n_5));
   HA1D0 g301__4733 (.A(counter_5_out[0]),
	.B(counter_5_out[1]),
	.CO(n_3),
	.S(n_4));
   HA1D0 g302__6161 (.A(counter_3_out[0]),
	.B(counter_3_out[1]),
	.CO(n_1),
	.S(n_2));
   DFKSND1 \u_counter_5bit_q_reg[0]  (.CP(clk),
	.D(rst),
	.Q(clk_maker_out[0]),
	.QN(UNCONNECTED6),
	.SN(clk_maker_out[0]));
   DFKCND1 \u_counter_5bit_q_reg[1]  (.CN(p1),
	.CP(clk),
	.D(n_5),
	.Q(clk_maker_out[1]),
	.QN(clk_4096k));
endmodule

module dual_thresholding (
	clk, 
	rst, 
	oc_in, 
	counter_5_out, 
	counter_3_out, 
	en_od);
   input clk;
   input rst;
   input [17:0] oc_in;
   input [4:0] counter_5_out;
   input [2:0] counter_3_out;
   output en_od;

   // Internal wires
   wire FE_OFN2_n_9;
   wire [17:0] oc_prev;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_81;
   wire onset_detected_already;
   wire sub_16_29_n_591;
   wire sub_16_29_n_594;
   wire sub_16_29_n_595;
   wire sub_16_29_n_596;
   wire sub_16_29_n_598;
   wire sub_16_29_n_599;
   wire sub_16_29_n_600;
   wire sub_16_29_n_601;
   wire sub_16_29_n_602;
   wire sub_16_29_n_603;
   wire sub_16_29_n_604;
   wire sub_16_29_n_605;
   wire sub_16_29_n_606;
   wire sub_16_29_n_607;
   wire sub_16_29_n_608;
   wire sub_16_29_n_609;
   wire sub_16_29_n_610;
   wire sub_16_29_n_611;

   BUFFD2 FE_OFC2_n_9 (.I(n_9),
	.Z(FE_OFN2_n_9));
   SDFKCNQD0 onset_detected_already_reg (.CN(n_8),
	.CP(clk),
	.D(onset_detected_already),
	.Q(onset_detected_already),
	.SE(n_19),
	.SI(n_0));
   DFKCNQD1 en_od_reg (.CN(n_0),
	.CP(clk),
	.D(n_18),
	.Q(en_od));
   OR2D0 g1258__9315 (.A1(n_17),
	.A2(rst),
	.Z(n_19));
   AO21D0 g1259__9945 (.A1(en_od),
	.A2(onset_detected_already),
	.B(n_17),
	.Z(n_18));
   NR2D0 g1260__2883 (.A1(n_16),
	.A2(onset_detected_already),
	.ZN(n_17));
   OAI33D0 g1261__2346 (.A1(oc_in[1]),
	.A2(oc_in[0]),
	.A3(n_15),
	.B1(n_5),
	.B2(n_31),
	.B3(n_12),
	.ZN(n_16));
   OR4D0 g1262__1666 (.A1(oc_in[5]),
	.A2(oc_in[3]),
	.A3(oc_in[2]),
	.A4(n_14),
	.Z(n_15));
   OR4D0 g1263__7410 (.A1(oc_in[6]),
	.A2(oc_in[7]),
	.A3(oc_in[4]),
	.A4(n_13),
	.Z(n_14));
   OR4D0 g1264__6417 (.A1(oc_in[15]),
	.A2(oc_in[12]),
	.A3(oc_in[13]),
	.A4(n_11),
	.Z(n_13));
   EDFKCNQD1 \oc_prev_reg[17]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[17]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[17]));
   EDFKCNQD1 \oc_prev_reg[0]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[0]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[0]));
   IND4D0 g1283__5477 (.A1(n_28),
	.B1(n_2),
	.B2(n_6),
	.B3(n_10),
	.ZN(n_12));
   OR4D0 g1284__2398 (.A1(oc_in[10]),
	.A2(oc_in[14]),
	.A3(oc_in[11]),
	.A4(n_7),
	.Z(n_11));
   INR4D0 g1285__5107 (.A1(n_4),
	.B1(n_34),
	.B2(n_35),
	.B3(n_81),
	.ZN(n_10));
   INVD1 g1286 (.I(n_8),
	.ZN(n_9));
   IND4D0 g1287__6260 (.A1(counter_3_out[1]),
	.B1(n_1),
	.B2(counter_3_out[0]),
	.B3(n_3),
	.ZN(n_8));
   OR4D0 g1288__4319 (.A1(oc_in[16]),
	.A2(oc_in[17]),
	.A3(oc_in[8]),
	.A4(oc_in[9]),
	.Z(n_7));
   NR3D0 g1289__8428 (.A1(n_33),
	.A2(n_26),
	.A3(n_23),
	.ZN(n_6));
   OR4D0 g1290__5526 (.A1(n_27),
	.A2(n_29),
	.A3(n_30),
	.A4(n_32),
	.Z(n_5));
   NR4D0 g1291__6783 (.A1(n_25),
	.A2(n_24),
	.A3(n_21),
	.A4(n_20),
	.ZN(n_4));
   NR4D0 g1292__3680 (.A1(counter_5_out[1]),
	.A2(counter_5_out[2]),
	.A3(counter_5_out[3]),
	.A4(counter_5_out[4]),
	.ZN(n_3));
   NR2D0 g1293__1617 (.A1(n_36),
	.A2(n_22),
	.ZN(n_2));
   NR2D0 g1294__2802 (.A1(counter_3_out[2]),
	.A2(counter_5_out[0]),
	.ZN(n_1));
   INVD1 g1295 (.I(rst),
	.ZN(n_0));
   OAI21D0 sub_16_29_g1080__8246 (.A1(sub_16_29_n_605),
	.A2(oc_prev[0]),
	.B(sub_16_29_n_591),
	.ZN(n_20));
   CKND2D0 sub_16_29_g1081__7098 (.A1(oc_prev[0]),
	.A2(sub_16_29_n_605),
	.ZN(sub_16_29_n_591));
   INVD1 sub_16_29_g1092 (.I(oc_in[0]),
	.ZN(sub_16_29_n_605));
   XNR2D1 g1297__1881 (.A1(oc_in[16]),
	.A2(sub_16_29_n_595),
	.ZN(n_36));
   XNR2D1 g1299__7482 (.A1(oc_in[15]),
	.A2(sub_16_29_n_604),
	.ZN(n_35));
   XNR2D1 g1301__6161 (.A1(oc_in[14]),
	.A2(sub_16_29_n_609),
	.ZN(n_34));
   XNR2D1 g1303__9945 (.A1(oc_in[13]),
	.A2(sub_16_29_n_600),
	.ZN(n_33));
   XNR2D1 g1305__2346 (.A1(oc_in[12]),
	.A2(sub_16_29_n_602),
	.ZN(n_32));
   XNR2D1 g1307__7410 (.A1(oc_in[11]),
	.A2(sub_16_29_n_611),
	.ZN(n_31));
   XNR2D1 g1309__5477 (.A1(oc_in[10]),
	.A2(sub_16_29_n_598),
	.ZN(n_30));
   XNR2D1 g1311__5107 (.A1(oc_in[9]),
	.A2(sub_16_29_n_601),
	.ZN(n_29));
   XNR2D1 g1313__4319 (.A1(oc_in[8]),
	.A2(sub_16_29_n_596),
	.ZN(n_28));
   XNR2D1 g1315__5526 (.A1(sub_16_29_n_603),
	.A2(oc_in[7]),
	.ZN(n_27));
   XNR2D1 g1317__3680 (.A1(sub_16_29_n_610),
	.A2(oc_in[6]),
	.ZN(n_26));
   XNR2D1 g1319__2802 (.A1(sub_16_29_n_599),
	.A2(oc_in[5]),
	.ZN(n_25));
   XNR2D1 g1321__5122 (.A1(sub_16_29_n_606),
	.A2(oc_in[4]),
	.ZN(n_24));
   XNR2D1 g1323__7098 (.A1(sub_16_29_n_608),
	.A2(oc_in[3]),
	.ZN(n_23));
   XNR2D1 g1325__1881 (.A1(sub_16_29_n_607),
	.A2(oc_in[2]),
	.ZN(n_22));
   XOR2D1 g2 (.A1(oc_in[17]),
	.A2(oc_prev[17]),
	.Z(n_81));
   EDFKCND1 \oc_prev_reg[1]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[1]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[1]),
	.QN(sub_16_29_n_594));
   EDFKCND1 \oc_prev_reg[16]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[16]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[16]),
	.QN(sub_16_29_n_595));
   EDFKCND1 \oc_prev_reg[8]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[8]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[8]),
	.QN(sub_16_29_n_596));
   EDFKCND1 \oc_prev_reg[10]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[10]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[10]),
	.QN(sub_16_29_n_598));
   EDFKCND1 \oc_prev_reg[5]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[5]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[5]),
	.QN(sub_16_29_n_599));
   EDFKCND1 \oc_prev_reg[13]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[13]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[13]),
	.QN(sub_16_29_n_600));
   EDFKCND1 \oc_prev_reg[9]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[9]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[9]),
	.QN(sub_16_29_n_601));
   EDFKCND1 \oc_prev_reg[12]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[12]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[12]),
	.QN(sub_16_29_n_602));
   EDFKCND1 \oc_prev_reg[7]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[7]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[7]),
	.QN(sub_16_29_n_603));
   EDFKCND1 \oc_prev_reg[15]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[15]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[15]),
	.QN(sub_16_29_n_604));
   EDFKCND1 \oc_prev_reg[4]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[4]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[4]),
	.QN(sub_16_29_n_606));
   EDFKCND1 \oc_prev_reg[2]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[2]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[2]),
	.QN(sub_16_29_n_607));
   EDFKCND1 \oc_prev_reg[3]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[3]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[3]),
	.QN(sub_16_29_n_608));
   EDFKCND1 \oc_prev_reg[14]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[14]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[14]),
	.QN(sub_16_29_n_609));
   EDFKCND1 \oc_prev_reg[6]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[6]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[6]),
	.QN(sub_16_29_n_610));
   EDFKCND1 \oc_prev_reg[11]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[11]),
	.E(FE_OFN2_n_9),
	.Q(oc_prev[11]),
	.QN(sub_16_29_n_611));
   XOR3D0 sub_16_29_g1079__1359 (.A1(sub_16_29_n_591),
	.A2(sub_16_29_n_594),
	.A3(oc_in[1]),
	.Z(n_21));
endmodule

module dual_thresholding_131 (
	clk, 
	rst, 
	oc_in, 
	counter_5_out, 
	counter_3_out, 
	en_od);
   input clk;
   input rst;
   input [17:0] oc_in;
   input [4:0] counter_5_out;
   input [2:0] counter_3_out;
   output en_od;

   // Internal wires
   wire [17:0] oc_prev;
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;
   wire n_30;
   wire n_31;
   wire n_32;
   wire n_33;
   wire n_34;
   wire n_35;
   wire n_36;
   wire n_81;
   wire onset_detected_already;
   wire sub_16_29_n_591;
   wire sub_16_29_n_594;
   wire sub_16_29_n_595;
   wire sub_16_29_n_596;
   wire sub_16_29_n_598;
   wire sub_16_29_n_599;
   wire sub_16_29_n_600;
   wire sub_16_29_n_601;
   wire sub_16_29_n_602;
   wire sub_16_29_n_603;
   wire sub_16_29_n_604;
   wire sub_16_29_n_605;
   wire sub_16_29_n_606;
   wire sub_16_29_n_607;
   wire sub_16_29_n_608;
   wire sub_16_29_n_609;
   wire sub_16_29_n_610;
   wire sub_16_29_n_611;

   SDFKCNQD0 onset_detected_already_reg (.CN(n_8),
	.CP(clk),
	.D(onset_detected_already),
	.Q(onset_detected_already),
	.SE(n_19),
	.SI(n_0));
   DFKCNQD1 en_od_reg (.CN(n_0),
	.CP(clk),
	.D(n_18),
	.Q(en_od));
   OR2D0 g1258__5115 (.A1(n_17),
	.A2(rst),
	.Z(n_19));
   AO21D0 g1259__7482 (.A1(en_od),
	.A2(onset_detected_already),
	.B(n_17),
	.Z(n_18));
   NR2D0 g1260__4733 (.A1(n_16),
	.A2(onset_detected_already),
	.ZN(n_17));
   OAI33D0 g1261__6161 (.A1(oc_in[1]),
	.A2(oc_in[0]),
	.A3(n_15),
	.B1(n_5),
	.B2(n_31),
	.B3(n_12),
	.ZN(n_16));
   OR4D0 g1262__9315 (.A1(oc_in[5]),
	.A2(oc_in[3]),
	.A3(oc_in[2]),
	.A4(n_14),
	.Z(n_15));
   OR4D0 g1263__9945 (.A1(oc_in[6]),
	.A2(oc_in[7]),
	.A3(oc_in[4]),
	.A4(n_13),
	.Z(n_14));
   OR4D0 g1264__2883 (.A1(oc_in[15]),
	.A2(oc_in[12]),
	.A3(oc_in[13]),
	.A4(n_11),
	.Z(n_13));
   EDFKCNQD1 \oc_prev_reg[17]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[17]),
	.E(n_9),
	.Q(oc_prev[17]));
   EDFKCNQD1 \oc_prev_reg[0]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[0]),
	.E(n_9),
	.Q(oc_prev[0]));
   IND4D0 g1283__2346 (.A1(n_28),
	.B1(n_2),
	.B2(n_6),
	.B3(n_10),
	.ZN(n_12));
   OR4D0 g1284__1666 (.A1(oc_in[10]),
	.A2(oc_in[14]),
	.A3(oc_in[11]),
	.A4(n_7),
	.Z(n_11));
   INR4D0 g1285__7410 (.A1(n_4),
	.B1(n_34),
	.B2(n_35),
	.B3(n_81),
	.ZN(n_10));
   INVD2 g1286 (.I(n_8),
	.ZN(n_9));
   IND4D1 g1287__6417 (.A1(counter_3_out[1]),
	.B1(n_1),
	.B2(counter_3_out[0]),
	.B3(n_3),
	.ZN(n_8));
   OR4D0 g1288__5477 (.A1(oc_in[16]),
	.A2(oc_in[17]),
	.A3(oc_in[8]),
	.A4(oc_in[9]),
	.Z(n_7));
   NR3D0 g1289__2398 (.A1(n_33),
	.A2(n_26),
	.A3(n_23),
	.ZN(n_6));
   OR4D0 g1290__5107 (.A1(n_27),
	.A2(n_29),
	.A3(n_30),
	.A4(n_32),
	.Z(n_5));
   NR4D0 g1291__6260 (.A1(n_25),
	.A2(n_24),
	.A3(n_21),
	.A4(n_20),
	.ZN(n_4));
   NR4D0 g1292__4319 (.A1(counter_5_out[1]),
	.A2(counter_5_out[2]),
	.A3(counter_5_out[3]),
	.A4(counter_5_out[4]),
	.ZN(n_3));
   NR2D0 g1293__8428 (.A1(n_36),
	.A2(n_22),
	.ZN(n_2));
   NR2D0 g1294__5526 (.A1(counter_3_out[2]),
	.A2(counter_5_out[0]),
	.ZN(n_1));
   INVD1 g1295 (.I(rst),
	.ZN(n_0));
   OAI21D0 sub_16_29_g1080__1617 (.A1(sub_16_29_n_605),
	.A2(oc_prev[0]),
	.B(sub_16_29_n_591),
	.ZN(n_20));
   CKND2D0 sub_16_29_g1081__2802 (.A1(oc_prev[0]),
	.A2(sub_16_29_n_605),
	.ZN(sub_16_29_n_591));
   INVD1 sub_16_29_g1092 (.I(oc_in[0]),
	.ZN(sub_16_29_n_605));
   XNR2D1 g1297__5122 (.A1(oc_in[16]),
	.A2(sub_16_29_n_595),
	.ZN(n_36));
   XNR2D1 g1299__7098 (.A1(oc_in[15]),
	.A2(sub_16_29_n_604),
	.ZN(n_35));
   XNR2D1 g1301__1881 (.A1(oc_in[14]),
	.A2(sub_16_29_n_609),
	.ZN(n_34));
   XNR2D1 g1303__7482 (.A1(oc_in[13]),
	.A2(sub_16_29_n_600),
	.ZN(n_33));
   XNR2D1 g1305__6161 (.A1(oc_in[12]),
	.A2(sub_16_29_n_602),
	.ZN(n_32));
   XNR2D1 g1307__9945 (.A1(oc_in[11]),
	.A2(sub_16_29_n_611),
	.ZN(n_31));
   XNR2D1 g1309__2346 (.A1(oc_in[10]),
	.A2(sub_16_29_n_598),
	.ZN(n_30));
   XNR2D1 g1311__7410 (.A1(oc_in[9]),
	.A2(sub_16_29_n_601),
	.ZN(n_29));
   XNR2D1 g1313__5477 (.A1(oc_in[8]),
	.A2(sub_16_29_n_596),
	.ZN(n_28));
   XNR2D1 g1315__5107 (.A1(sub_16_29_n_603),
	.A2(oc_in[7]),
	.ZN(n_27));
   XNR2D1 g1317__4319 (.A1(sub_16_29_n_610),
	.A2(oc_in[6]),
	.ZN(n_26));
   XNR2D1 g1319__5526 (.A1(sub_16_29_n_599),
	.A2(oc_in[5]),
	.ZN(n_25));
   XNR2D1 g1321__3680 (.A1(sub_16_29_n_606),
	.A2(oc_in[4]),
	.ZN(n_24));
   XNR2D1 g1323__2802 (.A1(sub_16_29_n_608),
	.A2(oc_in[3]),
	.ZN(n_23));
   XNR2D1 g1325__5122 (.A1(sub_16_29_n_607),
	.A2(oc_in[2]),
	.ZN(n_22));
   XOR2D1 g2 (.A1(oc_in[17]),
	.A2(oc_prev[17]),
	.Z(n_81));
   EDFKCND1 \oc_prev_reg[1]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[1]),
	.E(n_9),
	.Q(oc_prev[1]),
	.QN(sub_16_29_n_594));
   EDFKCND1 \oc_prev_reg[16]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[16]),
	.E(n_9),
	.Q(oc_prev[16]),
	.QN(sub_16_29_n_595));
   EDFKCND1 \oc_prev_reg[8]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[8]),
	.E(n_9),
	.Q(oc_prev[8]),
	.QN(sub_16_29_n_596));
   EDFKCND1 \oc_prev_reg[10]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[10]),
	.E(n_9),
	.Q(oc_prev[10]),
	.QN(sub_16_29_n_598));
   EDFKCND1 \oc_prev_reg[5]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[5]),
	.E(n_9),
	.Q(oc_prev[5]),
	.QN(sub_16_29_n_599));
   EDFKCND1 \oc_prev_reg[13]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[13]),
	.E(n_9),
	.Q(oc_prev[13]),
	.QN(sub_16_29_n_600));
   EDFKCND1 \oc_prev_reg[9]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[9]),
	.E(n_9),
	.Q(oc_prev[9]),
	.QN(sub_16_29_n_601));
   EDFKCND1 \oc_prev_reg[12]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[12]),
	.E(n_9),
	.Q(oc_prev[12]),
	.QN(sub_16_29_n_602));
   EDFKCND1 \oc_prev_reg[7]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[7]),
	.E(n_9),
	.Q(oc_prev[7]),
	.QN(sub_16_29_n_603));
   EDFKCND1 \oc_prev_reg[15]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[15]),
	.E(n_9),
	.Q(oc_prev[15]),
	.QN(sub_16_29_n_604));
   EDFKCND1 \oc_prev_reg[4]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[4]),
	.E(n_9),
	.Q(oc_prev[4]),
	.QN(sub_16_29_n_606));
   EDFKCND1 \oc_prev_reg[2]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[2]),
	.E(n_9),
	.Q(oc_prev[2]),
	.QN(sub_16_29_n_607));
   EDFKCND1 \oc_prev_reg[3]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[3]),
	.E(n_9),
	.Q(oc_prev[3]),
	.QN(sub_16_29_n_608));
   EDFKCND1 \oc_prev_reg[14]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[14]),
	.E(n_9),
	.Q(oc_prev[14]),
	.QN(sub_16_29_n_609));
   EDFKCND1 \oc_prev_reg[6]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[6]),
	.E(n_9),
	.Q(oc_prev[6]),
	.QN(sub_16_29_n_610));
   EDFKCND1 \oc_prev_reg[11]  (.CN(n_0),
	.CP(clk),
	.D(oc_in[11]),
	.E(n_9),
	.Q(oc_prev[11]),
	.QN(sub_16_29_n_611));
   XOR3D0 sub_16_29_g1079__1359 (.A1(sub_16_29_n_591),
	.A2(sub_16_29_n_594),
	.A3(oc_in[1]),
	.Z(n_21));
endmodule

module mux8X1 (
	inp0, 
	inp1, 
	inp2, 
	inp3, 
	inp4, 
	inp5, 
	inp6, 
	inp7, 
	sel, 
	out);
   input [9:0] inp0;
   input [9:0] inp1;
   input [9:0] inp2;
   input [9:0] inp3;
   input [9:0] inp4;
   input [9:0] inp5;
   input [9:0] inp6;
   input [9:0] inp7;
   input [2:0] sel;
   output [9:0] out;

   // Internal wires
   wire n_0;
   wire n_1;
   wire n_2;
   wire n_3;
   wire n_4;
   wire n_5;
   wire n_6;
   wire n_7;
   wire n_8;
   wire n_9;
   wire n_10;
   wire n_11;
   wire n_12;
   wire n_13;
   wire n_14;
   wire n_15;
   wire n_16;
   wire n_17;
   wire n_18;
   wire n_19;
   wire n_20;
   wire n_21;
   wire n_22;
   wire n_23;
   wire n_24;
   wire n_25;
   wire n_26;
   wire n_27;
   wire n_28;
   wire n_29;

   AO221D1 g1479__8246 (.A1(n_9),
	.A2(inp5[2]),
	.B1(n_5),
	.B2(inp3[2]),
	.C(n_29),
	.Z(out[2]));
   AO221D1 g1480__7098 (.A1(n_7),
	.A2(inp0[6]),
	.B1(n_4),
	.B2(inp2[6]),
	.C(n_28),
	.Z(out[6]));
   AO221D1 g1481__6131 (.A1(n_6),
	.A2(inp4[9]),
	.B1(n_8),
	.B2(inp1[9]),
	.C(n_21),
	.Z(out[9]));
   AO221D1 g1482__1881 (.A1(n_9),
	.A2(inp5[1]),
	.B1(n_5),
	.B2(inp3[1]),
	.C(n_26),
	.Z(out[1]));
   AO221D1 g1483__5115 (.A1(n_4),
	.A2(inp2[5]),
	.B1(n_9),
	.B2(inp5[5]),
	.C(n_22),
	.Z(out[5]));
   AO221D1 g1484__7482 (.A1(n_9),
	.A2(inp5[7]),
	.B1(n_5),
	.B2(inp3[7]),
	.C(n_23),
	.Z(out[7]));
   AO221D1 g1485__4733 (.A1(n_8),
	.A2(inp1[8]),
	.B1(n_9),
	.B2(inp5[8]),
	.C(n_27),
	.Z(out[8]));
   AO221D1 g1486__6161 (.A1(n_7),
	.A2(inp0[0]),
	.B1(n_4),
	.B2(inp2[0]),
	.C(n_25),
	.Z(out[0]));
   AO221D1 g1487__9315 (.A1(n_4),
	.A2(inp2[4]),
	.B1(n_5),
	.B2(inp3[4]),
	.C(n_24),
	.Z(out[4]));
   AO221D1 g1488__9945 (.A1(n_7),
	.A2(inp0[3]),
	.B1(n_4),
	.B2(inp2[3]),
	.C(n_20),
	.Z(out[3]));
   IOA21D1 g1489__2883 (.A1(n_8),
	.A2(inp1[2]),
	.B(n_18),
	.ZN(n_29));
   IOA21D1 g1490__2346 (.A1(n_6),
	.A2(inp4[6]),
	.B(n_19),
	.ZN(n_28));
   IOA21D1 g1491__1666 (.A1(n_7),
	.A2(inp0[8]),
	.B(n_15),
	.ZN(n_27));
   IOA21D1 g1492__7410 (.A1(n_6),
	.A2(inp4[1]),
	.B(n_16),
	.ZN(n_26));
   IOA21D1 g1493__6417 (.A1(n_5),
	.A2(inp3[0]),
	.B(n_13),
	.ZN(n_25));
   IOA21D1 g1494__5477 (.A1(n_7),
	.A2(inp0[4]),
	.B(n_14),
	.ZN(n_24));
   IOA21D1 g1495__2398 (.A1(n_6),
	.A2(inp4[7]),
	.B(n_11),
	.ZN(n_23));
   IOA21D1 g1496__5107 (.A1(n_8),
	.A2(inp1[5]),
	.B(n_12),
	.ZN(n_22));
   IOA21D1 g1497__6260 (.A1(n_5),
	.A2(inp3[9]),
	.B(n_17),
	.ZN(n_21));
   IOA21D1 g1498__4319 (.A1(n_5),
	.A2(inp3[3]),
	.B(n_10),
	.ZN(n_20));
   AOI222D0 g1499__8428 (.A1(n_8),
	.A2(inp1[6]),
	.B1(n_5),
	.B2(inp3[6]),
	.C1(inp5[6]),
	.C2(n_9),
	.ZN(n_19));
   AOI222D0 g1500__5526 (.A1(n_7),
	.A2(inp0[2]),
	.B1(n_6),
	.B2(inp4[2]),
	.C1(inp2[2]),
	.C2(n_4),
	.ZN(n_18));
   AOI222D0 g1501__6783 (.A1(n_4),
	.A2(inp2[9]),
	.B1(n_9),
	.B2(inp5[9]),
	.C1(inp0[9]),
	.C2(n_7),
	.ZN(n_17));
   AOI222D0 g1502__3680 (.A1(n_4),
	.A2(inp2[1]),
	.B1(n_8),
	.B2(inp1[1]),
	.C1(inp0[1]),
	.C2(n_7),
	.ZN(n_16));
   AOI222D0 g1503__1617 (.A1(n_6),
	.A2(inp4[8]),
	.B1(n_5),
	.B2(inp3[8]),
	.C1(inp2[8]),
	.C2(n_4),
	.ZN(n_15));
   AOI222D0 g1504__2802 (.A1(n_6),
	.A2(inp4[4]),
	.B1(n_9),
	.B2(inp5[4]),
	.C1(inp1[4]),
	.C2(n_8),
	.ZN(n_14));
   AOI222D0 g1505__1705 (.A1(n_9),
	.A2(inp5[0]),
	.B1(n_6),
	.B2(inp4[0]),
	.C1(inp1[0]),
	.C2(n_8),
	.ZN(n_13));
   AOI222D0 g1506__5122 (.A1(n_7),
	.A2(inp0[5]),
	.B1(n_6),
	.B2(inp4[5]),
	.C1(inp3[5]),
	.C2(n_5),
	.ZN(n_12));
   AOI222D0 g1507__8246 (.A1(n_7),
	.A2(inp0[7]),
	.B1(n_8),
	.B2(inp1[7]),
	.C1(inp2[7]),
	.C2(n_4),
	.ZN(n_11));
   AOI222D0 g1508__7098 (.A1(n_9),
	.A2(inp5[3]),
	.B1(n_6),
	.B2(inp4[3]),
	.C1(inp1[3]),
	.C2(n_8),
	.ZN(n_10));
   AN2XD1 g1509__6131 (.A1(n_3),
	.A2(sel[2]),
	.Z(n_9));
   NR2D1 g1510__1881 (.A1(n_2),
	.A2(sel[2]),
	.ZN(n_8));
   INR2D1 g1511__5115 (.A1(n_1),
	.B1(sel[2]),
	.ZN(n_7));
   AN2XD1 g1512__7482 (.A1(n_1),
	.A2(sel[2]),
	.Z(n_6));
   AN3XD1 g1513__4733 (.A1(n_0),
	.A2(sel[1]),
	.A3(sel[0]),
	.Z(n_5));
   INR3D1 g1514__6161 (.A1(sel[1]),
	.B1(sel[0]),
	.B2(sel[2]),
	.ZN(n_4));
   INVD1 g1515 (.I(n_2),
	.ZN(n_3));
   IND2D1 g1516__9315 (.A1(sel[1]),
	.B1(sel[0]),
	.ZN(n_2));
   NR2XD0 g1517__9945 (.A1(sel[0]),
	.A2(sel[1]),
	.ZN(n_1));
   INVD1 g1518 (.I(sel[2]),
	.ZN(n_0));
endmodule

module onset_detector (
	clk, 
	rst, 
	clk_rst, 
	channel_r1, 
	channel_r2, 
	channel_r3, 
	channel_r4, 
	channel_r5, 
	channel_r6, 
	onset_detected);
   input clk;
   input rst;
   input clk_rst;
   input [9:0] channel_r1;
   input [9:0] channel_r2;
   input [9:0] channel_r3;
   input [9:0] channel_r4;
   input [9:0] channel_r5;
   input [9:0] channel_r6;
   output [30:0] onset_detected;

   // Internal wires
   wire FE_OFN1_clk_4096k;
   wire FE_OFN0_clk_4096k;
   wire n_31;
   wire n_30;
   wire n_29;
   wire n_28;
   wire n_27;
   wire n_26;
   wire n_25;
   wire n_24;
   wire n_23;
   wire n_22;
   wire n_21;
   wire n_20;
   wire n_19;
   wire n_18;
   wire n_17;
   wire n_16;
   wire n_15;
   wire n_14;
   wire n_13;
   wire n_12;
   wire n_11;
   wire n_10;
   wire n_9;
   wire n_8;
   wire n_7;
   wire n_6;
   wire n_5;
   wire n_4;
   wire n_0;
   wire FE_DBTN0_rst;
   wire [17:0] \class_activity[0] ;
   wire [17:0] class1_add_in;
   wire [17:0] \class_activity_next[0] ;
   wire [9:0] mult_a;
   wire [7:0] class1_weight;
   wire [17:0] \class_activity[1] ;
   wire [17:0] class2_add_in;
   wire [17:0] \class_activity_next[1] ;
   wire [7:0] class2_weight;
   wire [2:0] counter_8_out;
   wire [4:0] counter_32_out;
   wire UNCONNECTED7;
   wire UNCONNECTED8;
   wire UNCONNECTED9;
   wire UNCONNECTED_HIER_Z;
   wire UNCONNECTED_HIER_Z0;
   wire UNCONNECTED_HIER_Z1;
   wire UNCONNECTED_HIER_Z2;
   wire UNCONNECTED_HIER_Z3;
   wire UNCONNECTED_HIER_Z4;
   wire UNCONNECTED_HIER_Z5;
   wire UNCONNECTED_HIER_Z6;
   wire UNCONNECTED_HIER_Z7;
   wire UNCONNECTED_HIER_Z8;
   wire UNCONNECTED_HIER_Z9;
   wire UNCONNECTED_HIER_Z10;
   wire UNCONNECTED_HIER_Z11;
   wire UNCONNECTED_HIER_Z12;
   wire UNCONNECTED_HIER_Z13;
   wire UNCONNECTED_HIER_Z14;
   wire UNCONNECTED_HIER_Z15;
   wire UNCONNECTED_HIER_Z16;
   wire UNCONNECTED_HIER_Z17;
   wire UNCONNECTED_HIER_Z18;
   wire UNCONNECTED_HIER_Z19;
   wire UNCONNECTED_HIER_Z20;
   wire clk_4096k;
   wire n_1;
   wire n_2;
   wire n_3;
   wire prev_clk_4096k;

   INVD3 FE_OFC1_clk_4096k (.I(FE_OFN0_clk_4096k),
	.ZN(FE_OFN1_clk_4096k));
   CKND0 FE_OFC0_clk_4096k (.I(clk_4096k),
	.ZN(FE_OFN0_clk_4096k));
   TIEL LTIELO_28 (.ZN(onset_detected[2]));
   TIEL LTIELO_27 (.ZN(onset_detected[3]));
   TIEL LTIELO_26 (.ZN(onset_detected[4]));
   TIEL LTIELO_25 (.ZN(onset_detected[5]));
   TIEL LTIELO_24 (.ZN(onset_detected[6]));
   TIEL LTIELO_23 (.ZN(onset_detected[7]));
   TIEL LTIELO_22 (.ZN(onset_detected[8]));
   TIEL LTIELO_21 (.ZN(onset_detected[9]));
   TIEL LTIELO_20 (.ZN(onset_detected[10]));
   TIEL LTIELO_19 (.ZN(onset_detected[11]));
   TIEL LTIELO_18 (.ZN(onset_detected[12]));
   TIEL LTIELO_17 (.ZN(onset_detected[13]));
   TIEL LTIELO_16 (.ZN(onset_detected[14]));
   TIEL LTIELO_15 (.ZN(onset_detected[15]));
   TIEL LTIELO_14 (.ZN(onset_detected[16]));
   TIEL LTIELO_13 (.ZN(onset_detected[17]));
   TIEL LTIELO_12 (.ZN(onset_detected[18]));
   TIEL LTIELO_11 (.ZN(onset_detected[19]));
   TIEL LTIELO_10 (.ZN(onset_detected[20]));
   TIEL LTIELO_9 (.ZN(onset_detected[21]));
   TIEL LTIELO_8 (.ZN(onset_detected[22]));
   TIEL LTIELO_7 (.ZN(onset_detected[23]));
   TIEL LTIELO_6 (.ZN(onset_detected[24]));
   TIEL LTIELO_5 (.ZN(onset_detected[25]));
   TIEL LTIELO_4 (.ZN(onset_detected[26]));
   TIEL LTIELO_3 (.ZN(onset_detected[27]));
   TIEL LTIELO_2 (.ZN(onset_detected[28]));
   TIEL LTIELO_1 (.ZN(onset_detected[29]));
   TIEL LTIELO (.ZN(onset_detected[30]));
   INVD1 FE_DBTC0_rst (.I(rst),
	.ZN(FE_DBTN0_rst));
   adder_18bit u1_adder_16bit (.a(\class_activity[0] ),
	.b(class1_add_in),
	.sum(\class_activity_next[0] ));
   mult10X8 u1_mult10X8 (.a(mult_a),
	.b({ class1_weight[7],
		class1_weight[6],
		class1_weight[5],
		UNCONNECTED_HIER_Z,
		class1_weight[4],
		class1_weight[2],
		class1_weight[1],
		class1_weight[0] }),
	.product(class1_add_in));
   adder_18bit_130 u2_adder_16bit (.a(\class_activity[1] ),
	.b(class2_add_in),
	.sum(\class_activity_next[1] ));
   mult10X8_132 u2_mult10X8 (.a(mult_a),
	.b({ class2_weight[7],
		class2_weight[6],
		class2_weight[5],
		UNCONNECTED_HIER_Z0,
		class2_weight[4],
		class2_weight[2],
		class2_weight[1],
		class2_weight[0] }),
	.product(class2_add_in));
   class1_top_channels u_class1_top_channels (.clk(FE_OFN1_clk_4096k),
	.rst(clk_rst),
	.channel({ counter_8_out,
		counter_32_out }),
	.channel_weight({ class1_weight[7],
		class1_weight[6],
		class1_weight[5],
		class1_weight[4],
		UNCONNECTED7,
		class1_weight[2],
		class1_weight[1],
		class1_weight[0] }));
   class2_top_channels u_class2_top_channels (.clk(FE_OFN1_clk_4096k),
	.rst(clk_rst),
	.channel({ counter_8_out,
		counter_32_out }),
	.channel_weight({ class2_weight[7],
		class2_weight[6],
		class2_weight[5],
		class2_weight[4],
		UNCONNECTED8,
		class2_weight[2],
		class2_weight[1],
		class2_weight[0] }));
   counter_gen u_counter_gen (.clk(clk),
	.rst(rst),
	.counter_3_out(counter_8_out),
	.counter_5_out(counter_32_out),
	.clk_4096k(clk_4096k),
	.p1(FE_DBTN0_rst));
   dual_thresholding u_dual_threshold_class1 (.clk(FE_OFN1_clk_4096k),
	.rst(clk_rst),
	.oc_in(\class_activity[0] ),
	.counter_5_out(counter_32_out),
	.counter_3_out(counter_8_out),
	.en_od(onset_detected[0]));
   dual_thresholding_131 u_dual_threshold_class2 (.clk(FE_OFN1_clk_4096k),
	.rst(clk_rst),
	.oc_in(\class_activity[1] ),
	.counter_5_out(counter_32_out),
	.counter_3_out(counter_8_out),
	.en_od(onset_detected[1]));
   mux8X1 u_mux8X1 (.inp0(channel_r1),
	.inp1(channel_r2),
	.inp2(channel_r3),
	.inp3(channel_r4),
	.inp4(channel_r5),
	.inp5(channel_r6),
	.inp6({ UNCONNECTED_HIER_Z10,
		UNCONNECTED_HIER_Z9,
		UNCONNECTED_HIER_Z8,
		UNCONNECTED_HIER_Z7,
		UNCONNECTED_HIER_Z6,
		UNCONNECTED_HIER_Z5,
		UNCONNECTED_HIER_Z4,
		UNCONNECTED_HIER_Z3,
		UNCONNECTED_HIER_Z2,
		UNCONNECTED_HIER_Z1 }),
	.inp7({ UNCONNECTED_HIER_Z20,
		UNCONNECTED_HIER_Z19,
		UNCONNECTED_HIER_Z18,
		UNCONNECTED_HIER_Z17,
		UNCONNECTED_HIER_Z16,
		UNCONNECTED_HIER_Z15,
		UNCONNECTED_HIER_Z14,
		UNCONNECTED_HIER_Z13,
		UNCONNECTED_HIER_Z12,
		UNCONNECTED_HIER_Z11 }),
	.sel(counter_8_out),
	.out(mult_a));
   EDFKCNQD1 \class_activity_reg[0][13]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [13]),
	.E(n_3),
	.Q(\class_activity[0] [13]));
   EDFKCNQD1 \class_activity_reg[0][8]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [8]),
	.E(n_3),
	.Q(\class_activity[0] [8]));
   EDFKCNQD1 \class_activity_reg[0][9]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [9]),
	.E(n_3),
	.Q(\class_activity[0] [9]));
   EDFKCNQD1 \class_activity_reg[0][10]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [10]),
	.E(n_3),
	.Q(\class_activity[0] [10]));
   EDFKCNQD1 \class_activity_reg[1][15]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [15]),
	.E(n_3),
	.Q(\class_activity[1] [15]));
   EDFKCNQD1 \class_activity_reg[1][16]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [16]),
	.E(n_3),
	.Q(\class_activity[1] [16]));
   EDFKCNQD1 \class_activity_reg[1][17]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [17]),
	.E(n_3),
	.Q(\class_activity[1] [17]));
   EDFKCNQD1 \class_activity_reg[0][11]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [11]),
	.E(n_3),
	.Q(\class_activity[0] [11]));
   EDFKCNQD1 \class_activity_reg[0][12]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [12]),
	.E(n_3),
	.Q(\class_activity[0] [12]));
   EDFKCNQD1 \class_activity_reg[0][0]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [0]),
	.E(n_3),
	.Q(\class_activity[0] [0]));
   EDFKCNQD1 \class_activity_reg[0][14]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [14]),
	.E(n_3),
	.Q(\class_activity[0] [14]));
   EDFKCNQD1 \class_activity_reg[0][15]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [15]),
	.E(n_3),
	.Q(\class_activity[0] [15]));
   EDFKCNQD1 \class_activity_reg[0][16]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [16]),
	.E(n_3),
	.Q(\class_activity[0] [16]));
   EDFKCNQD1 \class_activity_reg[0][17]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [17]),
	.E(n_3),
	.Q(\class_activity[0] [17]));
   EDFKCNQD1 \class_activity_reg[1][0]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [0]),
	.E(n_3),
	.Q(\class_activity[1] [0]));
   EDFKCNQD1 \class_activity_reg[1][1]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [1]),
	.E(n_3),
	.Q(\class_activity[1] [1]));
   EDFKCNQD1 \class_activity_reg[0][1]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [1]),
	.E(n_3),
	.Q(\class_activity[0] [1]));
   EDFKCNQD1 \class_activity_reg[0][2]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [2]),
	.E(n_3),
	.Q(\class_activity[0] [2]));
   EDFKCNQD1 \class_activity_reg[0][5]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [5]),
	.E(n_3),
	.Q(\class_activity[0] [5]));
   EDFKCNQD1 \class_activity_reg[1][3]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [3]),
	.E(n_3),
	.Q(\class_activity[1] [3]));
   EDFKCNQD1 \class_activity_reg[1][4]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [4]),
	.E(n_3),
	.Q(\class_activity[1] [4]));
   EDFKCNQD1 \class_activity_reg[1][5]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [5]),
	.E(n_3),
	.Q(\class_activity[1] [5]));
   EDFKCNQD1 \class_activity_reg[0][3]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [3]),
	.E(n_3),
	.Q(\class_activity[0] [3]));
   EDFKCNQD1 \class_activity_reg[1][6]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [6]),
	.E(n_3),
	.Q(\class_activity[1] [6]));
   EDFKCNQD1 \class_activity_reg[1][7]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [7]),
	.E(n_3),
	.Q(\class_activity[1] [7]));
   EDFKCNQD1 \class_activity_reg[1][8]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [8]),
	.E(n_3),
	.Q(\class_activity[1] [8]));
   EDFKCNQD1 \class_activity_reg[0][4]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [4]),
	.E(n_3),
	.Q(\class_activity[0] [4]));
   EDFKCNQD1 \class_activity_reg[1][2]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [2]),
	.E(n_3),
	.Q(\class_activity[1] [2]));
   EDFKCNQD1 \class_activity_reg[1][9]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [9]),
	.E(n_3),
	.Q(\class_activity[1] [9]));
   EDFKCNQD1 \class_activity_reg[1][10]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [10]),
	.E(n_3),
	.Q(\class_activity[1] [10]));
   EDFKCNQD1 \class_activity_reg[1][11]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [11]),
	.E(n_3),
	.Q(\class_activity[1] [11]));
   EDFKCNQD1 \class_activity_reg[0][6]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [6]),
	.E(n_3),
	.Q(\class_activity[0] [6]));
   EDFKCNQD1 \class_activity_reg[1][12]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [12]),
	.E(n_3),
	.Q(\class_activity[1] [12]));
   EDFKCNQD1 \class_activity_reg[1][13]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [13]),
	.E(n_3),
	.Q(\class_activity[1] [13]));
   EDFKCNQD1 \class_activity_reg[0][7]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[0] [7]),
	.E(n_3),
	.Q(\class_activity[0] [7]));
   EDFKCNQD1 \class_activity_reg[1][14]  (.CN(n_2),
	.CP(clk),
	.D(\class_activity_next[1] [14]),
	.E(n_3),
	.Q(\class_activity[1] [14]));
   CKAN2D4 g210__2883 (.A1(FE_OFN1_clk_4096k),
	.A2(prev_clk_4096k),
	.Z(n_3));
   OR4D2 g211__2346 (.A1(counter_32_out[2]),
	.A2(counter_32_out[3]),
	.A3(counter_32_out[4]),
	.A4(n_1),
	.Z(n_2));
   DFKCND1 prev_clk_4096k_reg (.CN(FE_DBTN0_rst),
	.CP(clk),
	.D(FE_OFN1_clk_4096k),
	.Q(UNCONNECTED9),
	.QN(prev_clk_4096k));
   OR2XD1 g213__1666 (.A1(counter_32_out[0]),
	.A2(counter_32_out[1]),
	.Z(n_1));
endmodule

